
#include <stddef.h>

// needs the typedef xpm_row_t
#include <lcom/xpm.h>

/* XPM */
static xpm_row_t const pewpew[] = {
/* columns rows colors chars-per-pixel */
"67 74 230 2 ",
"   c #000000",
".  c #030102",
"X  c #0B0202",
"o  c #0C0905",
"O  c #06020A",
"+  c #0A0509",
"@  c #0D090A",
"#  c #060804",
"$  c #140300",
"%  c #1C0300",
"&  c #1A0A02",
"*  c #140C0D",
"=  c #1B0D0E",
"-  c #110708",
";  c #16100C",
":  c #150C13",
">  c #190E14",
",  c #1A0E19",
"<  c #130613",
"1  c #161214",
"2  c #1B1314",
"3  c #161219",
"4  c #1C151B",
"5  c #1E1A1D",
"6  c #1D1916",
"7  c #230300",
"8  c #230A01",
"9  c #2C0C00",
"0  c #290502",
"q  c #320900",
"w  c #221305",
"e  c #2D1501",
"r  c #26130C",
"t  c #2C150A",
"y  c #331400",
"u  c #3C1300",
"i  c #371B05",
"p  c #221413",
"a  c #23141D",
"s  c #231A1C",
"d  c #2A1B1C",
"f  c #291717",
"g  c #321D14",
"h  c #351E18",
"j  c #3B2206",
"k  c #25211D",
"l  c #392417",
"z  c #1D1423",
"x  c #1E1B21",
"c  c #251520",
"v  c #241C22",
"b  c #2A1C24",
"n  c #2B1F2A",
"m  c #251C2A",
"M  c #311E24",
"N  c #252124",
"B  c #2B2225",
"V  c #2C232A",
"C  c #2D292C",
"Z  c #292827",
"A  c #322425",
"S  c #3C2A25",
"D  c #32252C",
"F  c #332A2D",
"G  c #3A2D2B",
"H  c #392523",
"J  c #3B312E",
"K  c #2D2B32",
"L  c #2E2633",
"P  c #342631",
"I  c #352B33",
"U  c #3A2C35",
"Y  c #3B2E39",
"T  c #382B36",
"R  c #353134",
"E  c #3B3335",
"W  c #3C323A",
"Q  c #3D393B",
"!  c #34323B",
"~  c #421D00",
"^  c #481E06",
"/  c #501F00",
"(  c #4A2301",
")  c #462702",
"_  c #522C03",
"`  c #5B2D03",
"'  c #4B3308",
"]  c #5D3302",
"[  c #583509",
"{  c #542A14",
"}  c #583615",
"|  c #493114",
" . c #632C00",
".. c #643403",
"X. c #633804",
"o. c #673B07",
"O. c #683E13",
"+. c #422E28",
"@. c #43322C",
"#. c #553927",
"$. c #41353D",
"%. c #413C3E",
"&. c #4B393C",
"*. c #513E33",
"=. c #402E30",
"-. c #6D450C",
";. c #774A0B",
":. c #684315",
">. c #774914",
",. c #785518",
"<. c #7C500D",
"1. c #554228",
"2. c #4A413C",
"3. c #57443B",
"4. c #6B4C28",
"5. c #7A5625",
"6. c #795836",
"7. c #634931",
"8. c #443641",
"9. c #443B43",
"0. c #493D45",
"q. c #4B3F49",
"w. c #454243",
"e. c #4D424A",
"r. c #4A464A",
"t. c #50444D",
"y. c #534B4B",
"u. c #534751",
"i. c #584D55",
"p. c #555154",
"a. c #5C545A",
"s. c #5E5B5D",
"d. c #595553",
"f. c #61575E",
"g. c #615A5E",
"h. c #6D5C5A",
"j. c #6D5E4F",
"k. c #635B62",
"l. c #695E65",
"z. c #646364",
"x. c #6A6465",
"c. c #6B6469",
"v. c #6D6B6C",
"b. c #696B67",
"n. c #716A6F",
"m. c #72676F",
"M. c #736B71",
"N. c #747273",
"B. c #7C767A",
"V. c #7D7A7B",
"C. c #7B7676",
"Z. c #895714",
"A. c #8D621E",
"S. c #9F6B1F",
"D. c #A26A12",
"F. c #845D29",
"G. c #8A5C25",
"H. c #955F23",
"J. c #87642A",
"K. c #966829",
"L. c #876537",
"P. c #946A33",
"I. c #9E7234",
"U. c #A2692A",
"Y. c #A9792B",
"T. c #B37F2D",
"R. c #A77738",
"E. c #B17C38",
"W. c #8D6B49",
"Q. c #977956",
"!. c #A57B42",
"~. c #AB7C42",
"^. c #AF7E4B",
"/. c #A57554",
"(. c #897B67",
"). c #81767E",
"_. c #807B7E",
"`. c #B9852B",
"'. c #B78839",
"]. c #B18A3A",
"[. c #C48D22",
"{. c #C99627",
"}. c #C18D36",
"|. c #C89737",
" X c #D29A2E",
".X c #AC874A",
"XX c #B88947",
"oX c #A88359",
"OX c #B68B55",
"+X c #BB9254",
"@X c #BB9757",
"#X c #BC9048",
"$X c #A88362",
"%X c #BA8B67",
"&X c #BB9669",
"*X c #BDA06F",
"=X c #938574",
"-X c #C5984B",
";X c #C69956",
":X c #D19F42",
">X c #CFA348",
",X c #D8A649",
"<X c #C9A258",
"1X c #D5A559",
"2X c #C79968",
"3X c #CEA66A",
"4X c #D4A564",
"5X c #D5A76C",
"6X c #DEB66A",
"7X c #D8A975",
"8X c #DAB476",
"9X c #CAA476",
"0X c #E8BA6E",
"qX c #E4B874",
"wX c #E2A96C",
"eX c #EAC37A",
"rX c #837B82",
"tX c #8A8688",
"yX c #9C9392",
"uX c #A79A94",
"iX c #AF9FA3",
"pX c #A7A6A7",
"aX c #BAADB2",
"sX c #DCB986",
"dX c #E8C180",
"fX c #C0B6C6",
"gX c #D2CAD3",
"hX c #D2C8CD",
"jX c #E5D7E6",
"kX c #F2E5F6",
/* pixels */
"                                                                                                                                      ",
"                                                                                                                                      ",
"                                                                                                                                      ",
"                                                                                                                                      ",
"                                                                                                                                      ",
"                                                                                                                                      ",
"                                                                                                                                      ",
"                                                                                                                                      ",
"                                      pXtXv.s.Q 5 + . . . . . . . . . . . . . . . N w.d.C.tXpX                                        ",
"                                pXz.v . @ . @ C 9.Q w.y.r.r.r.w.r.r.r.r.r.w.w.w.w.%.F . . . . Z z.pX                                  ",
"                              uX. . 5 Q r.p.s.p.Q I N v 4 4 5 5 3 1 3 3 4 5 v B R Q d.p.a.p.E 5 + . pX                                ",
"                              v.+ 9.Q z.z.s.s.p.Q V 1 @ . . . . . . . . . . @ 3 B Q p.s.a.s.x.Q w.. v.                                ",
"                              v.. Q V g.M.n.v.c.c.z.k.k.k.k.g.k.a.a.f.f.a.a.k.c.c.M.c.c.n.l.f.Q %.. B.                                ",
"                              v.@ F V C R y.c.n.M.B.V.V.B.B.B.V.).B.).).rXrXrXrXB.M.B.m.a.8.W E %.. N.                                ",
"                              z.. I C v I v 1 v I 9.r.p.f.f.f.l.l.k.k.k.k.f.k.k.a.q.t.e.W D U U E + N.                                ",
"                              v.. E N B B C I F D F B v b V b b v v b v v b I $.W i.t.e.e.D U W %.. N.                                ",
"                              v.. E N N B F V V I U U U U U U U U U U U U Y 8.q.e.t.0.e.$.D U T Q . v.                                ",
"                              z.. F C B v s v D A D D P U U Y Y U U U T I I Y 8.W 9.9.$.W I I I E . N.                                ",
"                              V.. F v N s D D D D D U U P P P P P P P P I U W 8.0.0.q.$.$.U D F %.+ B.                                ",
"                                d.@ s s s b V b A D P U U U Y U Y U U T I T U W 0.W W U I V B s . s.                                  ",
"                                  x.X b > * > a a c b n n n n n n V V n n V D P D V b n c 4 V . c.                                    ",
"                                  g.* F V V V a a c c c c a a a 4 4 a c b V I U Y $.Y P V V %.. v.                                    ",
"                                  w.. F V v b D n n D D D D P P D D V V I Y $.$.$.e.8.D V V W + y.                                    ",
"                                  . V F I I I D U U U P D D P P P P P P U $.q.q.e.t.q.I E T %.V N                                     ",
"                                  . I F V V V I U U U U U Y Y Y Y Y Y Y W q.u.u.t.i.q.W W W W Q O                                     ",
"                                C.. F F V D V D U U U U U U Y Y Y Y Y U W 0.t.t.u.a.t.I I W $.8.. _.                                  ",
"                                E p F F V D D D U U U U U T U U Y T T U W q.e.e.u.t.e.W U W U 9.2 R                                   ",
"                                . E D D D V F D U U U U U U U Y Y T T T W 0.e.e.t.u.e.I D W W 8.I .                                   ",
"                              s.. E V D V V D I Y Y W Y U Y Y Y W T T Y W 9.e.e.t.q.q.W U W U W W * z.                                ",
"                              . C N D F d D V I U U Y U U Y Y Y Y T T Y U $.0.q.e.q.0.$.U I U U W C #                                 ",
"                            v.. Q v D V b F V D U U U U U U Y Y U I T U U W 9.q.q.i.q.U n P 8.U E E . v.                              ",
"                            . C B V b a A V D F U U U U U U U U G G G U I E %.q.e.0.0.f.t.n D E E I V .                               ",
"                          b.. E 5 N M A b F I I U D D U U D &.S l i l +.J E 2.2.9.e.L kXjX+ I E E I 9.. N.                            ",
"                          + d N v V M d D I T I D U @.S % 8 % e ' ' y 8 % & 1.2.0.e.m fXgXO $.E I F R R 1                             ",
"                        V.. I b B b a D U I x R F H % % L.@X3X8X6XeXqX5X.XJ.8 % *.&.e.b . 8.s F I U U W . rX                          ",
"                        R c v b b b a U V B E J g 8 L.8XdXeXqX<X<X<X<XqXeXqX3XL.0 | 3.G tXgXyX2 I U D 9.@ 0.                          ",
"                        + C c b b n b n A D @.% i 2XqXqX.XF.o._ ) ) } O.F..X5XqX#X^ ) j uXhXaXn.p U U U D O                           ",
"                      C.. I b n m b a d =.+.% } 7XqX-X;.( u 9 % $ & 8 9 ~ ( ;.;X0X-X` 7 (.aXaXtX- $.A U U O M.                        ",
"                      R ; R 6 v z m v A H i ( 7XwXR...~ % $ $ X o X X $ % % j [ R.wX4Xu #.yXiXl.s V E I T 1 r.                        ",
"                      # C Z 5 x z m 4 H l 7 %X5XU. .u % X X . . . . . . X $ $ i _ ~.0XXX7 #.h.$.v R I I I V .                         ",
"                    tX# C k v x z c s S % W.7XE...u % X X X # . . . . . . # X X e [ ~.4XF.% *.W K K ! K I ! .                         ",
"                    V.. J s 5 4 v p s g 0 &X;X;.u 7 X . # # . . . . . . . . # . $ i >.4X+Xy #.2.T ! V L I W . tX                      ",
"                    d.o A * a b B = d 8 4.3XI._ % $ . # . . . . . . . . . . . . . $ } P.1X<.9 3.E Y V U I G * y.                      ",
"                  yXo w $ g h f r f l % !.;X<.y $ X . . . . . . . . . . . . . . . X i L.-XI.7 #.3.H H @.g % w &                       ",
"                  (.l oX4.7 7 7 % l h 9 XX'.X.7 $ . . . . . . . . . . . . . . . . X % } XX;Xq } #.h 8 7 y 4.Q.j                       ",
"                  (.j &X@X+X!.F.} 7 7 _ -XY.-.8 $ . . . . . . . . . . . . . . . . @ $ #.!.XX/ q ~ O.F..XOX;X@X)                       ",
"                  (.) .X'.}.:X,X1XqXOX` #XY.o.7 $ . . . . . . . . . . . . . . . # # & #.!.#X..OX4X6X,X,X}.'.'.)                       ",
"                  (.' @X'.{.[.[.{.|.-X..`.Y.-.7 $ . . . . . . . . . . . . . . . . o X 7.R.'...;X1X}.[.{.[.`.-X_                       ",
"                  =X8 *X;X|.{. X{. X`. .`.T.-.7 & X . # # . . . . . . . . . . . . o $ 6.R.E.` XX}. X{. X|.>X@X9                       ",
"                    & 1..X@X>X>X,X>X}...D.`.K.9 $ X . . . # . . . . # . . . . . . X % Q.R.S...;X,X|.,X,X>X].[ e                       ",
"                    y.$ 8 } L..X@X<X8X;.Z.T.T.( 8 $ X . . . . . # . . . . . . # . X j oXR.Z.<.8X<X;X!.F.[ % $ j.                      ",
"                    x.X +.% % % 0 } 6.X.<.U.'.A.7 8 X @ . # . # . # + . . . # . * 8 6..X].X.-.5.[ y 7 % e l $ x.                      ",
"                    rX+ F p f g w $ % % ~ P.Y.#X0 7 % X . . . . # . . . . . + X $ y &X~.Z.~ y % l l +.l d E X                         ",
"                      O c b * a 2 2 s h % 6.A.;X^.0 9 % X X X # . . . o . . X = 9 $X;XK.5.7 l S A U I b V V +                         ",
"                      3 x 1 c > > 4 5 * p e J.A.1XR.0 7 8 X X . . o . . o p % 9 /.2XH.G.7 t @.F U V I z m z N                         ",
"                      z.. V : 4 3 * 1 s > $ ) F.K.4XoX0 7 % e t = = & w & % 7 %X7XK.G._ 8 S A v V I V V L O c.                        ",
"                        . N 1 ; 2 * 5 : a p $ } ,.P.3X3XI.u 7 % % % 8 % i W.7X7XH.Z.` 7 l k B v b V N v C O                           ",
"                        %.# 6 6 o 6 2 c , = f $ ' :.,.+XwX7X9XoX$XQ.oX9XsX8X.X;.>./ 7 g f N 2 V V v v V + w.                          ",
"                          . F * 2 2 : < , p = f X i } :.>.~.OX5X7X7X5X+XP.,.-.o.u 7 t f d s b 2 B F Z F .                             ",
"                            . F 2 1 , c : @ 2 = 2 & % i } [ ..o.O.:.o...X.[ ) 7 e 8 d b 2 s b s v 5 C .                               ",
"                            v . B 2 > , 4 a 2 4 > v p $ % 9 ^ ^ { { { i 9 0 8 t d s 2 s 2 s 2 d v C . K                               ",
"                              o o N 4 : 3 : : 4 , < a p a f % 7 7 7 % 8 r r p d > 4 v * s p s s V . +                                 ",
"                                . @ F 5 O 4 4 : > 4 * > * : p r 8 r p 2 6 s 4 > 4 4 4 5 4 4 4 C . c                                   ",
"                                    . 5 C < 4 > 2 @ 6 * 2 4 2 2 p 2 3 4 1 1 4 1 3 3 3 v 3 v @ O                                       ",
"                                      . . @ N c 4 5 3 1 2 4 4 1 2 1 1 3 1 1 3 x 5 v C v . . x                                         ",
"                                          N . + O 1 N V v 5 5 N v v x N 5 5 5 N v . . .                                               ",
"                                                    . . + + . . . . . . . . . + .                                                     ",
"                                                                                                                                      ",
"                                                                                                                                      ",
"                                                                                                                                      ",
"                                                                                                                                      ",
"                                                                                                                                      ",
"                                                                                                                                      ",
"                                                                                                                                      "
};

/* XPM */
static xpm_row_t const plane[] = {
/* columns rows colors chars-per-pixel */
"130 87 239 2 ",
"   c #000000",
".  c #030200",
"X  c #0A0500",
"o  c #0C0B01",
"O  c #050B00",
"+  c #120D02",
"@  c #110D08",
"#  c #0D1303",
"$  c #0C1408",
"%  c #131204",
"&  c #15140A",
"*  c #1A150B",
"=  c #151A0D",
"-  c #1C1A0D",
";  c #171705",
":  c #1C1C12",
">  c #171D12",
",  c #221B0F",
"<  c #221C13",
"1  c #1C230C",
"2  c #1C2216",
"3  c #1D251B",
"4  c #17291E",
"5  c #232314",
"6  c #242B14",
"7  c #24241B",
"8  c #2A251C",
"9  c #24291D",
"0  c #2C2B1D",
"q  c #282516",
"w  c #312D1E",
"e  c #2D341C",
"r  c #2A3315",
"t  c #2C2D19",
"y  c #1B2C22",
"u  c #172C22",
"i  c #1D3429",
"p  c #1F3C30",
"a  c #242C22",
"s  c #2B2C23",
"d  c #292720",
"f  c #322D23",
"g  c #342F28",
"h  c #2C3125",
"j  c #2D332B",
"k  c #26372B",
"l  c #333325",
"z  c #343924",
"x  c #33352C",
"c  c #3A352A",
"v  c #353A2D",
"b  c #3B3B2C",
"n  c #3A3726",
"m  c #283C32",
"M  c #353B33",
"N  c #3B3C33",
"B  c #393C35",
"V  c #423D2E",
"C  c #423E34",
"Z  c #3D422D",
"A  c #3A4326",
"S  c #2A4436",
"D  c #3C4135",
"F  c #34443A",
"G  c #3C433A",
"H  c #374539",
"J  c #41482E",
"K  c #434334",
"L  c #444A35",
"P  c #44443A",
"I  c #4A463A",
"U  c #464B3C",
"Y  c #4B4C3C",
"T  c #4A4536",
"R  c #4C523D",
"E  c #495235",
"W  c #51563E",
"Q  c #524C3E",
"!  c #394B42",
"~  c #395A4C",
"^  c #3D5D53",
"/  c #3E6255",
"(  c #4C4E43",
")  c #464A42",
"_  c #514E42",
"`  c #524E48",
"'  c #4D5243",
"]  c #4C534B",
"[  c #45544A",
"{  c #535444",
"}  c #555A45",
"|  c #53534B",
" . c #5A554B",
".. c #545A4C",
"X. c #5B5C4C",
"o. c #5A5746",
"O. c #455D54",
"+. c #545B52",
"@. c #5D5D51",
"#. c #575953",
"$. c #635E53",
"%. c #61594C",
"&. c #5D624C",
"*. c #48675B",
"=. c #5B6254",
"-. c #5C635B",
";. c #556353",
":. c #636454",
">. c #656B54",
",. c #646559",
"<. c #646A5C",
"1. c #6B6B5B",
"2. c #696858",
"3. c #6C735C",
"4. c #6B7156",
"5. c #737A5E",
"6. c #71765D",
"7. c #696954",
"8. c #476D64",
"9. c #536C64",
"0. c #457266",
"q. c #45746C",
"w. c #4B746C",
"e. c #4A7468",
"r. c #53736B",
"t. c #527A6E",
"y. c #567367",
"u. c #4C7A72",
"i. c #497770",
"p. c #587C71",
"a. c #6C6D62",
"s. c #656961",
"d. c #726D63",
"f. c #6D7363",
"g. c #697468",
"h. c #737564",
"j. c #757B64",
"k. c #797E64",
"l. c #757B6A",
"z. c #7A7D6B",
"x. c #77756A",
"c. c #7C7C73",
"v. c #767B76",
"b. c #657E73",
"n. c #837C6E",
"m. c #827E74",
"M. c #5A8276",
"N. c #778165",
"B. c #7B8265",
"V. c #7C836B",
"C. c #7B856B",
"Z. c #7E8471",
"A. c #79877A",
"S. c #6A8479",
"D. c #77815F",
"F. c #81856D",
"G. c #828A6D",
"H. c #808266",
"J. c #838473",
"K. c #848A73",
"L. c #888D75",
"P. c #84847A",
"I. c #858A7B",
"U. c #8B8C7C",
"Y. c #8A8578",
"T. c #928D7C",
"R. c #8D927C",
"E. c #8A9176",
"W. c #91977E",
"Q. c #7A9386",
"!. c #779689",
"~. c #8C8C82",
"^. c #868B83",
"/. c #918D83",
"(. c #8D9281",
"). c #88978C",
"_. c #939384",
"`. c #959B84",
"'. c #94948A",
"]. c #9B9B8C",
"[. c #979989",
"{. c #999B93",
"}. c #8C9F92",
"|. c #A29D92",
" X c #A19C8E",
".X c #9CA38B",
"XX c #9DA292",
"oX c #96A699",
"OX c #8DA395",
"+X c #A3A395",
"@X c #A6AB9B",
"#X c #ABAC9C",
"$X c #A6A797",
"%X c #ADB29C",
"&X c #AAAE97",
"*X c #9BB2A7",
"=X c #96B7AB",
"-X c #A9ABA2",
";X c #B3AEA5",
":X c #A9B3A7",
">X c #B2B4A4",
",X c #B7B8A8",
"<X c #BBBCB3",
"1X c #ACBFB3",
"2X c #C3BDB4",
"3X c #C3BEAD",
"4X c #BDC2AC",
"5X c #BDC5B7",
"6X c #ADC4BA",
"7X c #C2C5B5",
"8X c #CACCBC",
"9X c #C5C8B9",
"0X c #CDD2BD",
"qX c #CED1BB",
"wX c #BDD1C7",
"eX c #CBCBC3",
"rX c #C9D4C9",
"tX c #D2D4C3",
"yX c #DBDBCC",
"uX c #D6D8C8",
"iX c #D9DCD3",
"pX c #D2CDC3",
"aX c #E4DBD2",
"sX c #DAE1CC",
"dX c #D8E4D8",
"fX c #EBECDC",
"gX c #E5E5D7",
"hX c #EDF3DC",
"jX c #EDEAD8",
"kX c #ECECE5",
"lX c #F4ECE5",
"zX c #EEF2E3",
"xX c #F4F4EC",
"cX c #FBFDEC",
"vX c #F5F7E6",
"bX c #FDFDF3",
"nX c #FFFFFA",
"mX c #F8F7F1",
"MX c #DDF0E5",
/* pixels */
"                                                                                                                                                                                                                                                                    ",
"                                                                                                                                                                                                                                                                    ",
"                                                                                                                                                                                                                                                                    ",
"                                                                                                                                                                                                                                                                    ",
"                                                                                                                                                                                                                                                                    ",
"                                                                                                                            7X2X                                                                                                                                    ",
"                                                                                                                3X+XP.z.,.{ I L I Y _ 2.z.T.#X                                                                                                                      ",
"                                                                                                            _.z.@.v 9 7 2 2 ; & & & & - 5 x } ,.J.;X                                                                                                                ",
"                                                                                                        _.{ ; O # # 3 G ..-.s.s.g.s.<.U h 9 # . % b x.;X                                                                                                            ",
"                                                                                                      ,.8 % = h G [ g.A.A.Q.).).}.}.}.oX}.^.A.g...9 : c n.                                                                                                          ",
"                                                                                                     .s & 2 j G +.g.A.Q.A.A.Q.Q.Q.).OX*X:X*X:X:X-Xg.v 5 8 1.                                                                                                        ",
"                                                                                                  T o 9 ( +.] H S ~ *.9.*.*.*.*.*.*.8.r.p.b.Q.*XwXiX5XA.: X Y                                                                                                       ",
"                                                                                                 .8 7 N ] ) H m S ~ *.y.r.*.8.8.*.*.*.8.8.*.9.S.).wXdXeXI.h o $.                                                                                                    ",
"                                                                                              I & 8 I I U H F m S ^ 8.p.t.0.e.e.0.0.0.0.8./ *.r.b.wXMXdXiXA.h X z.                                                                                                  ",
"                                                                                              + X 0 ( P D k k i S ^ r.M.t.0.e.i.u.u.u.i.i.0.0.8.p.6XwXrXkXrXI.% x ].                                                                                                ",
"                                                                                            T . 8 v B v M k k m S ~ e.t.0.0.e.0.q.i.i.i.i.0.i.0.p.!.=X*X6XrX9X..> b                                                                                                 ",
"                                                                                            * * d P M h h k m S S ~ e.t.e.e.w.i.q.q.q.i.i.q.w.w.w.t.!.1X!.*X5XOXa # (.                                                                                              ",
"                                                                                          ) X 8 N B M h j M S S S ~ 8.t.0.w.i.u.i.i.i.i.q.q.q.q.0.e.!.=Xp.y.}.5X=.# ,.                                                                                              ",
"                                                                                          c X N I B B x M F F S S ~ e.t.0.w.w.u.w.i.q.q.q.q.i.q.e.t.!.OX8.O.S.rX).v h +X                                                                                            ",
"                                                                                          8 o P P C P M D H H S S ~ e.t.0.e.w.w.0.q.q.q.q.q.i.q.q.u.M.M.*.*.y.6XoX;.$ c.                                                                                            ",
"                                                                                          * o C P P P M H F F S S ~ e.t.e.w.w.i.q.q.i.q.q.q.q.q.q.t.e.0.*.^ *.*X:Xs.O s.                                                                                            ",
"                                                                                        I & & P P B B x M F S k m ~ e.M.t.t.w.w.w.w.q.i.q.q.q.q.e.u.i.0.0.~ *.oX*Xg.O =.                                                                                            ",
"                                                                                        V * < C N x M j M F F k i ! r.M.t.t.w.w.0.w.q.i.q.q.e.q.i.u.q.0.0./ *.Q.}.g.$ <.                                                                                            ",
"                                                                                        g < 5 M N B M M D ! F k i ! 8.p.r.r.w.w.w.t.w.i.e.0.0.e.e.e.0.0.e.*.*.Q.Q.g.> g.                                                                                            ",
"                                                                                        f < 8 c B B B B D D M k u S ~ *.r.e.r.8.r.w.w.w.0.0.0.w.w.0.0.e.t.*.*.S.).g.k I.                                                                                            ",
"                                                                                        8 < d c B B M M M k k u u i i ! *.9.y.y.r.r.r.r.r.w.w.r.t.t.t.M.M.e.9.Q.Q.y.v g.@X@X                                                                                        ",
"                                              ;X                                        < < f M B M x B j a 4 u k 4 4 k *.y.y.y.9.9.y.y.y.r.r.r.r.t.t.p.t.r.y.A.S.*.a U { I x.                                                                                      ",
"                                        $X%.n n b f c o.                                < < g M B M x G j a 4 k H i 4 i *.9.9.9.O.O.O.O.O.O.O.O.O.^ ^ *.*.O.*.y.;.H 2 2 & X *  .                                                                                    ",
"                                      $.q X ; Y 2.$.{ l <  .                            < < x N B N M P x a 3 M ) k y i *.*.~ ! m k k m M F m m k i i p p m S F M a > > 2 8 % * I                                                                                   ",
"                                    n.X + _ 1.'.#X+X|.x.b ;  .                          < < l N N N M G x a 9 j H k y a O.[ S m u 4 y y y a y y u u u u 4 4 4 u 3 3 s 9 l x - X + x.                                                                                ",
"                                   Xf % d.aXcXfXyXpXtXgX8XY -  .                        f : f N M B B G x a a k j k y k [ ! m m k k a a a a j m F ! ! m i y y 3 a a d h N c c q X 8 _.                                                                              ",
"                                  n.q  .,XbXbX<Xz.h.h._.yX>X@.-                         c : l N M B B B M j j j a j H G +.! k k k k M j h j B [ -.g.9.[ F F m j h h 7 0 s : f g , o T                                                                               ",
"                                  1.5 +XfXcXvX@X:.{ o.h.XXyX].0 {                       C : 8 P M B B x M B M s a G ( =.+.D M a 3 j M G M M [ -.v.g.+.H ! ) [ j h h 8 8 5 < d x g X < d.8X                                                                          ",
"                                >Xo.0 ,XcXvXgX>XP.z.J.j.:.,X<Xx.- x.                    P : 8 K B M x s x x M x h B @.-.] D j 3 3 a B ) ] ] -.v.^.g.D a D ] ( 3 2 s 0 8 d s l f f * & d P.uXjX                                                                      ",
"                                #XT ; U.uXcXvX+Xd.z.h.z.z.U._._.l L                   ^.( f 8 8 x P M x x B P P M B M D B a 3 M ( ] +.] ] s.{.rXiX-Xg.G M D P 9 : : s d x x 8 7 < * o . + C z.,XgXfX                                                                ",
"                                $XV % 2.#XgXvX>Xh.h.j.h.(.h.Z._.} l a.        P. .P I C 8 8 8 d v P B M M B G M h s j M j 3 2 j ] s.v.v.A.^.-X5X5X).g.+.) M h 2 2 7 s d x x : o X d P | 8 o * ` '.eXgXlXlX                                                          ",
"                                 XV + $._.3XyX>XK.h.z.Z.Z.h.z.U.X.K K     2.5 X % l l 8 + * 8 D D x G G B M x a 3 a x x s a j a M -.{.:X:X{.).^.v.g.-.+.) j 2 = 9 h x h x x : X * @.;XeX'.( & . <  .$XpXlXlX                                                        ",
"                                T.n q 2.F.Y.T.z.h.J.L.U.z.J.[.+Xh.K - - ; 5 Y J.;XyXfX8XU.x . & x U P ) B v h a a j B B h j B a 3 B +.v.{.{.-X{.).).v.+.j 9 a a s 9 a : O . : ( '.gXxXkXgXeX].) : o < | ].uXlXkX                                                    ",
"                                n.l q z._.F.h.&.} X.1.1.z.R.I.,.b 5 % 5 I z.>XtXgXfXyXuX8XI.P 5 > 7 h B x s s h M h s x j j G ) G G ] +.s.s.v.v.P.^.a.P 3 3 h h 7 = $ $ 2 P Z.<XgXiX9X@X:X<X5X{.| X . @ x d.;XaXlX                                                  ",
"                                z.f 0 z._.Y.z.o.K K { &.1.3.Y 0 o - K U.tXzXcXgX8X#X_.[.7X<X].( > o : h s 7 s M D h j j j B U +.-.s.<.] G M G ] -.-.+.B 3 2 2 2 > = > 2 =.>XzXbXdX'.a.,.-.s.~.<XP.g 7 : X @ P '.yXlX                                                ",
"                                h.n w J.T.T.z.:.W R } R z - . # :.+X8XfXvX8X].L.J.V.j.j.z.(.$X$Xl.U 2 $ & : M ) D U =.-.U M M ( ) ] | s.s.<.<...( +.] M 9 2 # . # h <.XXsXzXsX@XV.3.l.I...h h '.x.B x./.c.. . 8  .,XlX                                              ",
"                              pX1.l V T._.J.h.&.} { z - o 0 Y z.,X0X0X4X$XL.k.j.j.j.j.3.3.j.(.XX[.I.<.v 9 h D x a U g.^.=.9 = D G v h v v B G a > 9 2 $ $ 2 x L 3.(.4X0X0X,X`.N.3.3.C.I.>.U U ].a.h {.iXuXm.x . + _ /.aX                                            ",
"                              8X2.w n T. XY.z.X.Y b - # 0 J.4XtXtX,X_.j.&.&.6.B.B.B.j.V.V.k.j.V._.XX_.l.=.U v 9 9 G f.Z.+.a = j x s 2 > = > 7 > = 9 3 2 9 L f.XX5XsXtX,XR.3.&.4.N.C.C.Z.l.l.Z.-X,.3 -XxXnXxX-X( & . c |.uXgX                                        ",
"                              8X$.w b U.$X XY.o.q o 6 3.,XgXtX&XL.z.h.H.K.F.V.B.B.B.B.B.V.V.z.z.J.U.U.XXXXZ.<.X.' ] D v 9 s h v x D U ..] [ ..-.g.c.(.XX,X8XyXuX,X`.j.>.>.j.N.N.N.h.h.j.Z.U.(.XX+.v ;XkXnXnXnXuXa.* X  .2XlXgX                                      ",
"                                :.w b T.$XU.Q q , z L.4X8X#X`.L.z.7.3.H.L.B.5.B.F.B.B.B.k.B.V.z.V.V.l.Z.K.Z.Z.l.f.h.l.<.=.<.f.f.f.l.(.XX@X@X:X<X5X9X5X7X4X:X@XXXI.j.3.>.j.C.N.j.V.K.N.3.j.U.[.U.) M 9XxXbXkXbXnXeXc.g * ;XmXlXlX                                    ",
"                                2.w K U._.2.- % b K.7X7X[.3.3.j.j.k.F.F.B.5.B.G.B.5.B.B.F.V.k.j.k.V.J.l.f.j.Z.Z.Z.(.(.R.I.R.(.(.[.{.-X,X4X5X9X9X5X5X<X#X[.Z.3.&.:.3.V.V.K.C.N.N.C.K.K.j.j.U.XXg.j x rXnXmXiXkXbXbX<X` X d.2XaXlXlX                                  ",
"                                1.f K X.T q - K F.<X[.L.k.k.F.F.k.k.5.k.H.B.B.D.B.B.B.B.B.B.V.F.F.V.z.Z.V.V.Z.V.l.V.Z.z.V.V.l.l.l.l.j.h.j.l.l.l.f.h.h.f.j.j.j.3.j.N.j.N.N.j.N.C.N.N.C.Z.V.K.Z.v 7 +.gXnXxXkXkXkXnX;X| : X 8 m.aXmX                                  ",
"                                d.l - f 0 q C X.1.h.z.h.k.z.j.k.V.B.H.B.k.B.B.B.B.D.B.B.B.B.B.B.V.V.l.K.V.j.N.l.j.j.z.l.V.l.l.l.l.j.l.j.j.h.f.j.l.l.l.l.j.j.j.C.N.j.V.V.N.C.C.B.j.V.C.Z.V.K.A.h 9 s.kXnXxXkXkXkXnX-X#.& ) C * $.2XlX                                ",
"                                z.f X o < N X.1.X.I 1.z.K.V.j.k.k.k.B.B.B.B.B.B.B.B.B.B.B.B.B.V.V.V.j.V.V.V.V.j.h.N.C.C.C.V.Z.Z.Z.V.V.C.C.V.Z.Z.Z.Z.Z.V.j.j.C.V.B.5.N.B.B.N.N.B.C.B.C.C.V.K.l.2 j A.kXnXkXkXkXxXbX-X( < '.$XN * $.yX                                ",
"                                Y.b X & d ) 2.1.,.,.x.J.L.V.k.B.F.F.B.k.B.B.B.B.B.B.B.B.B.B.B.V.V.V.k.V.j.j.V.V.V.V.C.V.V.V.Z.K.Z.Z.C.C.V.V.V.Z.Z.Z.V.V.K.K.V.j.j.j.j.N.B.B.B.B.C.B.N.N.K.K.f.# M {.zXnXkXkXkXxXbX|.C : 2XxXuX_ -  .yX                              ",
"                                o.q * < x { x.x.z.P.z.V.V.V.k.k.V.V.k.k.k.B.B.B.B.B.B.B.B.B.B.V.V.V.j.V.V.V.V.V.B.V.V.V.V.V.V.Z.K.K.K.K.K.K.Z.Z.Z.V.Z.V.l.V.j.j.B.G.j.j.B.B.B.C.V.V.j.N.R.K.:.O G >XxXnXkXkXxXmXbX{.N : ,XbXbXpXx.C ].qX                            ",
"                              P.8 - d 8 l ( P.U.U._.J.V.z.V.V.V.V.V.k.k.B.B.B.B.B.B.B.B.B.B.V.V.V.V.V.V.B.j.V.G.G.G.G.K.K.K.K.C.V.C.V.V.C.V.Z.Z.K.L.L.V.V.V.V.V.j.j.j.j.B.B.V.V.V.V.V.V.R.Z.X.. ( 9XxXbXkXxXmXbXbX~.c 5 ,XbXkXbX#Xf o.>X                            ",
"                              T % : d : 5 Y ~._.U.U.(.L.F.V.V.V.V.V.V.B.B.B.B.B.B.B.B.B.B.V.V.V.V.V.L.V.3.5.G.W.W.E.G.G.C.B.5.4.4.4.>.:.>.3.6.3.j.Z.Z.V.V.V.V.K.K.G.B.k.B.V.V.B.V.F.V.V._.Z.] O ..uXxXmXxXxXmXbXbXP.7 8 <XbXgXyX~.f T #XjX                          ",
"                              n + % f : d @.].'.U.~.I.L.K.L.L.K.V.k.V.V.B.B.B.B.B.B.B.B.B.V.V.V.V.V.V.V.V.G.G.G.B.>.E E J A e e e e e 6 6 6 6 1 6 e z L &.3.K.R.R.V.F.B.k.B.F.V.V.F.V.K.[.z.K & a.gXmXmXxXmXmXmXcXc.8 x _.,X+XJ.I - 2.3XjX                          ",
"                              g - * 5 : 8 ( a.,.@.@.:.2.6.z.K.L.K.V.k.B.B.B.B.B.B.B.B.B.B.V.V.V.V.V.V.K.R.B.} L Z A e r r r r e A J E R E L A z e z e e z A R >.V.K.L.F.k.V.F.F.F.F.F.K.R.3.b 9 P.xXbXxXxXmXmXmXxX1.7 x z.+XP.K : f #XaX                            ",
"                              < * < 8 8 8 s l l 0 5 h n K { >.j.V.V.j.k.B.B.B.V.V.B.B.B.B.V.V.V.V.V.R.E.V.R 1 # 1 r A A J E W >.j.G.W..X.X.X`.R.L.V.h.&.Z 1 ; 6 } V.R.F.k.V.F.F.F.F.J.K.L.:.l n '.bXbXxXxXmXmXxXkX@.* I P./.h.% 5 J.gX                              ",
"                              * * * & 8 s s s I Y Y b 0 # . 1 J h.K.K.V.B.B.B.B.B.V.V.k.F.k.k.z.K.V.:.L 6 # 6 >.&X%X.XG.5.B.G.V.G.E.W.W.`..X+X$X%X>X4X9X>X.XB.J 6 e W F.[.V.F.K.V.K.J.J.V.} 0 K $XbXbXbXbXbXbXbXgXX.% _ U.1.+ q m.                                  ",
"                            ,.+ * c $.d.d.X.{ a.I._.J.h.1.} z 0 { h.K.V.B.F.F.B.k.V.k.V.V.J.R.L.h.} z r 6 J K.7XgX4X`.E.G.L.L.G.G.G.G.G.L.R.W.`..X+X+X.X0XyX7X&Xh.L J 6.R.V.V.F.V.F.K.L.J.R 5 { ,XbXkXgXiXiXuX8X$XT & I { T V h.9X                                  ",
"                            f * C m.,X,X+XY.P.'.@X#X,X9XvXuXj.1 Z h.K.V.k.V.V.j.j.k.B.V.j.L.R.z.} z 0 Z 2.%XhXcXjXE.>.5.B.B.5.5.B.5.j.B.k.k.j.j.j.j.&.W %XsXvXcXtXR.Z } V.z.z.z.V.z.L.U.V.L - ,.,XfX9X>X+X+X_.J.:.0 5 0 q Y _.                                      ",
"                        P.- -  .'.2X9X+XJ.a.x.z.x.1.z.,XcXtXV.0 &.J.K.V.j.j.j.5.5.j.3.V.R.R.2.z Z R 3.V.&XgXvXhX7Xk.4.B.G.G.k.B.B.k.B.V.B.B.k.B.B.5.6.j..X0XcXcXhX%XR } V.R.U.K.L.V.z.z.h.K - <.[.>XI.h.,.z.U.U.2.w . q 2.].                                        ",
"                        q 8  .{.2X2X;X/.m.c.P.x.a.1.$XyX8Xz.Z z V.L.V.V.V.k.B.V.V.k.F.K.L.>.b 6 } 3.J.+XtXvXcX0XR.5.k.B.G.B.5.5.B.k.j.k.k.j.k.B.B.j.6.V.L.4XhXvXsX[.z L 3.V.j.f.h.:.&.&.X.Z 1 :.z.L.J.z.h.z.U.U.:., ; $.                                            ",
"                      Y : 1.{.,X;X/.P.J.U.~.P.x.I.+XfXuX1.0 ; K z.F.3.j.V.V.V.F.V.j.R.W.V.b 1 Z z.R.Z.4XfXcXvX%X>.B.B.5.B.B.B.B.B.B.B.B.B.B.B.B.B.k.5.4.F.,XhXcX>XR ; b :.:.X.X.&.Y L L L z 1 =.z.P.P.P.P.P._.P._ - K                                               ",
"                    1.b I c.{.{.P.,.{ $.1.a.h._.8XvX8Xh.% % e } &.X.} &.7.4.3.3.3.7.K.j.Y 6 z z.L.U.R.uXcXvXuXW.&.B.B.k.B.B.B.5.k.k.k.k.k.B.B.B.B.B.k.4.`.qXcXgXj.; ; Z } R Y Y } L L L b 0 6 1.L.U.U.U._.'.$Xm.8 , x.                                              ",
"                    C T _./.m.d.| ) I { _ Y  .U.>X7X1.5 ; z } } R K L Y R { { { } X.} L 0 z :.[.z.J.7XfXcXhX&Xj.>.4.B.5.k.B.B.B.B.B.B.B.B.B.B.k.B.B.4.k.,XjXcX#XZ O e L R L L L { { ' { n 6 e h.R.I.Y.U.'._.U.X.X Y +X                                              ",
"                  _ < Q |._.h. .I V T _ I v K @.1.2.5 ; K X.:.{ T K b Y K K Y L ' ..n ; 2 =.(.(.Z.].zXcXcXuXk.7.k.4.5.B.B.B.5.B.B.B.B.B.B.B.5.B.k.4.6.E.uXvXsX} 1 # L R ' ' U R { ' { ..l 5 v V.[.U.U.U.Y.U. .0 + n.                                                ",
"                  o.+ , $.n.Y.h.{ C b I Y v 0 0 - o c { 2. .{ K K { Y K I { U ( @.( 7 = U J.(.Z.[.9XcXcXgX%X3.3.V.5.5.B.B.5.B.B.B.B.D.B.B.B.B.V.B.} k.,XhXsXR.1 # z R R R ' ' U ( L U ( 0 q L U.]._.'.J.:.I & + T ;X                                                ",
"                    Q , , n T C q , q q - % & 8 c C _ X.X.o.T L Y } ( Y Y { ] | ] n 9 v Z.[.P.h.,XzXbXcX8XR.3.V.E.G.B.k.5.5.B.B.B.B.B.D.N.B.B.j.B.7..XfXhX#XK O 1 ' &.} R { ] Y L D K U 0 0 Y P._.P.,.Y q + o n [.                                                  ",
"                      2.T T V V n I T c q & % q b Y _ { I { _ { } Y Y } ' L ] | D 9 N <.{.(.x.I.tXcXvXhX,Xz.j.F.L.K.V.B.B.B.B.k.k.B.B.N.N.B.k.j.k.R.8XbX8X<.% 1 v } ..' R ] } ' U D N P 0 0 Y 2.$.Q l & . * Y Y.                                                    ",
"                                        x.Y < X X % f Y T I {  ._ { _ { { ( ] U x 9 | P.].Z.Z.>XfXbXvXyX+X3.j.B.k.B.F.V.V.B.B.k.B.B.B.B.B.V.h.z.V.,XfXzXI.0 . h ' } R R Y ] ] ' ' I N D 9 9 b V q % X + f n.                                                        ",
"                                            '.$.T w - - % : d b P ( Y  . .#.:.N > v x.'.I.c.'.tXxXbXvX7XU.>.j.V.k.B.V.V.F.V.B.B.B.V.j.j.V.V.3.h._.gXzX+Xl o - { =...' ' ' ] ' Y Y K N v - o o o + & Q x.|.                                                          ",
"                                                  m.,.c 8 < - : q 8 0 I Y ( #.l * | ^.'.l.P.-XfXcXxXuX.Xz.3.j.F.F.F.B.V.F.B.B.V.B.B.k.V.Z.j.<.J.9XcX5X' X & D ..X.' ( L L L K n l 8 q q & % - 0 o.x. X                                                              ",
"                                                          2.C < X . X - 0 l x 8 l a.P.P.x.~.9XcXbXfX%XV.h.h.j.V.V.V.V.F.F.B.V.V.B.j.z.R.U.2.1.$XxXyXc.: & h U N b N K x l v l 5 - o o ; 8 Y d./.                                                                    ",
"                                                                c. .P c 0 * * : I ^.~.c.c.>XgXlXbXyX[.V.j.j.V.V.j.h.3.3.6.4.>.6.j.j.V.Z.3.:.$XgXbXP.0 o 7 x x l l 9 - : - + X o - q Y d./.                                                                          ",
"                                                                        c.` - 5 #.'.'.P.^.8XcXbXbX8XJ.j.j.V.J.K.F.G.B.V.L.L.K.L.V.j.z.1.@.c.pXlX2XC . . : 8 : % & - - % % < l I :.z.;X                                                                              ",
"                                                                            N N x.].^.P.XXiXbXcXfX<Xh.1.j.J.L.R.W.[..X+X%X>X%X%X$X].U.:.1.,XfX<X` o . & * & X X & < 0 f I P.                                                                                        ",
"                                                                            b P x.c.,...f.{.9X7X-XJ.X.} :.>.1.3.k.L.R.W..X%X,X0XtXuX7X7XuXkX2X,.X + g c.P.v.                                                                                                        ",
"                                                                            x c :.,.| { =.h.I.U.J.,.} Y R R Y R W &.&.&.2.6.V.].@X>X>XuXfXpXd.< . d.                                                                                                                ",
"                                                                            8 - I  .:.,.a.<.:.:.1.:.L Z Z Z b z z Z z e z z b L L I h._.|.d.* . `                                                                                                                   ",
"                                                                            f 0 $.~.]._.~.I.U.J.J.f.Y K L R Y Y L R R L Y R { { L D c c 8 + <                                                                                                                       ",
"                                                                            < < X.|.$X+X].{.XX(.U.h.R L Y { } } } X.{ Y Y R Y K 0 - % + + |                                                                                                                         ",
"                                                                            c ; V x.U._.~.'._.P.P.z.' Y ( { ..{ Y I K b z l e 5 ; % 7                                                                                                                               ",
"                                                                              w X + I d.x.d.2.2.1.{ I K K P D l 0 9 - % o o & s.                                                                                                                                    ",
"                                                                                v.N < l g f 0 w f - & & & - - 5 x                                                                                                                                                   ",
"                                                                                      s.c f c C #.                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                    ",
"                                                                                                                                                                                                                                                                    ",
"                                                                                                                                                                                                                                                                    "
};

/* XPM */
static xpm_row_t const aim[]  = {
/* columns rows colors chars-per-pixel */
"60 60 24 1 ",
"  c #000000",
". c #74b72e",
"X c #74b72e",
"o c #74b72e",
"O c #74b72e",
"+ c #74b72e",
"@ c #74b72e",
"# c #74b72e",
"$ c #74b72e",
"% c #74b72e",
"& c #74b72e",
"* c #74b72e",
"= c #74b72e",
"- c #74b72e",
"; c #74b72e",
": c #74b72e",
"> c #74b72e",
", c #74b72e",
"< c #74b72e",
"1 c #74b72e",
"2 c #74b72e",
"3 c #74b72e",
"4 c #74b72e",
"5 c #74b72e",
/* pixels */
"                                                            ",
"                             :                              ",
"                             :                              ",
"                             ;3                             ",
"                         ;%%%+%;%%;;                        ",
"                     :%%;;   ;3    ;%%;                     ",
"                   ;%;       :        :%%                   ",
"                 ;%;         :           %%                 ",
"                %;           %;            %;               ",
"              :%        ;%%%;%;;%%%;;       ;%              ",
"             ;%      :%%;    :      ;%;      :%             ",
"            ;%      %;       :        :%;      %            ",
"           ;%     ;%                    ;%:     %           ",
"          :%     %;                       %;     %          ",
"          %     %:                         ;;    ;;         ",
"         %:    %                            %;    %:        ",
"        :%    %:                             %;    %        ",
"        %    ;;                               %    ;;       ",
"       ;;    %               3                 %    %       ",
"       %    %                :                 ;;   ;;      ",
"       %    %                :                  %    %      ",
"      ;    %                 ;:                 ;:   %      ",
"      %    %              ;%%+%%%                %   ;;     ",
"      %   ;;             %;  :4  %;              %    %     ",
"     :;   %             %:   :    ;;             ;    %     ",
"     ;:   %            ;;    :     %             ;;   %     ",
"     ;    %            %     :      %             ;   ;     ",
"     %    %           :;     :      %             %   ;:    ",
"     +   ;%           ;:     ;:     %:            %   %%    ",
"  %++.++++++%      ;;;+%;;;;;+%;;;;;+%;;:      ;+++++++++%  ",
"     +   :;           ;:     :4     ;             ;   %;    ",
"     ;    %            ;     :      %             %   ;:    ",
"     ;    %            %     :     :;             ;   ;     ",
"     ;:   %            :%    :     %             ;;   %     ",
"     :;   ;             ;%   :    %:             %    %     ",
"      %   ;;             ;%; ;: ;%               %    %     ",
"      %    %               ;%++%;                ;   ;;     ",
"      ;;   ;                 ;3                 %    %      ",
"       %    %                :                  %    %      ",
"       %    ;:               :                 %    ;:      ",
"       :;    %                                ;;    %       ",
"        %    ;%                               %    ;;       ",
"         %    ;;                             %     %        ",
"         ;;    %;                           %:    %         ",
"          %     %;                         %;    ;;         ",
"           %     ;%                       %:    ;%          ",
"            %     :%;                   ;%     :%           ",
"            :%      ;%:      :        ;%;     ;%            ",
"              %       ;%;:   ;4    ;%%;      ;%             ",
"               %;        ;%%%+%%%%%;        %;              ",
"                ;%           %:           ;%:               ",
"                  %%         :          ;%;                 ",
"                    %%;      :        ;%;                   ",
"                      ;%%;;  ;:  :;;%%:                     ",
"                          ;;%+%;%;;                         ",
"                             :4                             ",
"                             :                              ",
"                                                            ",
"                                                            ",
"                                                            "
};

/* XPM */
static xpm_row_t const explosion1[] = {
/* columns rows colors chars-per-pixel */
"27 25 231 2 ",
"   c #000000",
".  c #9A351F",
"X  c #B1371B",
"o  c #8E2A2B",
"O  c #9D2725",
"+  c #9B2C22",
"@  c #992C24",
"#  c #9B2E27",
"$  c #9A272B",
"%  c #9B262D",
"&  c #942B2B",
"*  c #962A2B",
"=  c #972A2B",
"-  c #932B2C",
";  c #932A2D",
":  c #932A2F",
">  c #95292D",
",  c #97282C",
"<  c #95282F",
"1  c #96282F",
"2  c #96292F",
"3  c #942B2E",
"4  c #932C2F",
"5  c #952E2D",
"6  c #99292F",
"7  c #9A292F",
"8  c #9C292D",
"9  c #9F282D",
"0  c #9F2A2D",
"q  c #9C282E",
"w  c #953323",
"e  c #993724",
"r  c #8C2C3B",
"t  c #892D3D",
"y  c #972731",
"u  c #972534",
"i  c #972634",
"p  c #972735",
"a  c #9A2530",
"s  c #9A2531",
"d  c #9B2531",
"f  c #982730",
"g  c #9A2630",
"h  c #9C2630",
"j  c #992535",
"k  c #982634",
"l  c #992634",
"z  c #982635",
"x  c #9B2437",
"c  c #982637",
"v  c #9B2736",
"b  c #932831",
"n  c #932931",
"m  c #932B31",
"M  c #922B32",
"N  c #952830",
"B  c #972830",
"V  c #962931",
"C  c #942833",
"Z  c #962832",
"A  c #972833",
"S  c #932834",
"D  c #902936",
"F  c #932836",
"G  c #922837",
"H  c #932837",
"J  c #922B37",
"K  c #952834",
"L  c #952934",
"P  c #952836",
"I  c #952A36",
"U  c #922C36",
"Y  c #992830",
"T  c #992831",
"R  c #992C34",
"E  c #972539",
"W  c #942639",
"Q  c #972739",
"!  c #96253A",
"~  c #95273A",
"^  c #98253A",
"/  c #98263B",
"(  c #9F243B",
")  c #912939",
"_  c #912B38",
"`  c #912B39",
"'  c #93293A",
"]  c #972938",
"[  c #932C39",
"{  c #91293C",
"}  c #92293C",
"|  c #952B3C",
" . c #992838",
".. c #982839",
"X. c #923134",
"o. c #9B3232",
"O. c #A02728",
"+. c #AE2628",
"@. c #AE282B",
"#. c #A92E2A",
"$. c #B12F27",
"%. c #B12D2C",
"&. c #A8302B",
"*. c #AC312F",
"=. c #B13E2F",
"-. c #A12A33",
";. c #A12E31",
":. c #A52B3A",
">. c #A1373F",
",. c #B03032",
"<. c #B53D30",
"1. c #C53A2C",
"2. c #D03C2E",
"3. c #C03F3A",
"4. c #D23D31",
"5. c #9D4434",
"6. c #A2432D",
"7. c #BD482E",
"8. c #AB592D",
"9. c #B65928",
"0. c #AE473C",
"q. c #B04D39",
"w. c #B8483B",
"e. c #BC5539",
"r. c #BF622F",
"t. c #CA5217",
"y. c #C35524",
"u. c #DD5625",
"i. c #C14037",
"p. c #C34236",
"a. c #C44035",
"s. c #CE413C",
"d. c #D74732",
"f. c #D84530",
"g. c #DC4431",
"h. c #DC4932",
"j. c #E14F2C",
"k. c #F54D26",
"l. c #F15A26",
"z. c #F85F27",
"x. c #F45D2C",
"c. c #E04D30",
"v. c #EE4F35",
"b. c #E74F39",
"n. c #E8563A",
"m. c #EA533C",
"M. c #F35435",
"N. c #F35635",
"B. c #C4662E",
"V. c #CC6F3A",
"C. c #DF6333",
"Z. c #D2673A",
"A. c #CA7234",
"S. c #F66B21",
"D. c #F46827",
"F. c #F6632E",
"G. c #FA612F",
"H. c #F47526",
"J. c #E06636",
"K. c #E66A3B",
"L. c #F56230",
"P. c #FE6534",
"I. c #F7703F",
"U. c #973644",
"Y. c #913B45",
"T. c #903B47",
"R. c #933A49",
"E. c #954042",
"W. c #9B4053",
"Q. c #9A4E5A",
"!. c #9D5D53",
"~. c #9B555D",
"^. c #9C555D",
"/. c #AF4F41",
"(. c #A34956",
"). c #A84B50",
"_. c #A55055",
"`. c #B15351",
"'. c #994F60",
"]. c #9C5960",
"[. c #A3606C",
"{. c #AD656A",
"}. c #A36373",
"|. c #A46571",
" X c #A06674",
".X c #AE6A73",
"XX c #AF6B78",
"oX c #D27B4C",
"OX c #E36943",
"+X c #C97A66",
"@X c #DC8B3E",
"#X c #D98D3F",
"$X c #F4842A",
"%X c #E48635",
"&X c #E98532",
"*X c #F38B31",
"=X c #F98D30",
"-X c #FC9E37",
";X c #FFA63B",
":X c #D78F56",
">X c #EA9842",
",X c #E79E5B",
"<X c #E29E5E",
"1X c #F29B53",
"2X c #FAA84A",
"3X c #F8BB4D",
"4X c #FAB84E",
"5X c #E6A054",
"6X c #F1AC57",
"7X c #FCA759",
"8X c #FCB654",
"9X c #FCB955",
"0X c #D88767",
"qX c #CE9375",
"wX c #D5907F",
"eX c #D59979",
"rX c #E59F6A",
"tX c #EAA065",
"yX c #E3AB6E",
"uX c #F8BE62",
"iX c #E1B775",
"pX c #AC7781",
"aX c #B5858C",
"sX c #B7868D",
"dX c #BB8C90",
"fX c #BE9199",
"gX c #D89980",
"hX c #C08E94",
"jX c #E3BB99",
"kX c #E9C18B",
"lX c #E3C5A4",
/* pixels */
"                                                      ",
"                                                      ",
"                                                      ",
"                                                      ",
"                        ~.Y.Y.'.        jX            ",
"                    pXU < K ~ { U.hXqX6XyX            ",
"        iX          ) a S ) x a < 8.4X>X              ",
"        kX4X#XeX  ^.~ ~ A 4 < < o.,X@XgX              ",
"          :X8XV.R K S q 2.OX7.6 < 5 ).                ",
"            /.* x a M *.c.7Xy.-.T t W.                ",
"            _.A x ( S A X 1Xt.g.@.M a [ [.            ",
"            E.K A * T a.N.l.D.L.C.9.e.>.{  X          ",
"            ].) i i.%.f.P.S.=X-X*X&XJ.q S r           ",
"              |  .s.1.$.I.H.$X;Xx.k.v.q M A aX        ",
"              `.6 :.3.. u.G.z.F.j.N.d.h x i |.        ",
"              +X=.A e <XZ.n.b.4.+.&.@ x i )           ",
"              tXq.w oXB.+ O.O $ q 6.: : X.}.          ",
"              !.o 0.i.m.h.,.~ M 5.uXr.w.              ",
"                S : % #.<.;.~ x @ A.9XK.              ",
"                Q.S ] / / x y K {.wX%X2X0X            ",
"                  aXR. .a * < (.      rX5X            ",
"                      fXXX.XdX            lX          ",
"                                                      ",
"                                                      ",
"                                                      "
};

/* XPM */
static xpm_row_t const explosion2[]= {
/* columns rows colors chars-per-pixel */
"39 38 207 2 ",
"   c #000000",
".  c #942E1D",
"X  c #982D1F",
"o  c #9A3B1B",
"O  c #98321A",
"+  c #AA391B",
"@  c #B1341E",
"#  c #9E2727",
"$  c #932D26",
"%  c #992C24",
"&  c #9C262D",
"*  c #952A2D",
"=  c #9A2A2D",
"-  c #983724",
";  c #8E2A37",
":  c #962634",
">  c #9A2633",
",  c #942933",
"<  c #9A2932",
"1  c #952739",
"2  c #992639",
"3  c #942939",
"4  c #982D39",
"5  c #8E313D",
"6  c #953333",
"7  c #933039",
"8  c #9B3831",
"9  c #A22D24",
"0  c #A1252E",
"q  c #A32A2B",
"w  c #AB2D2B",
"e  c #B62C2B",
"r  c #A7342D",
"t  c #AA3629",
"y  c #B4342B",
"u  c #B8382D",
"i  c #A22A33",
"p  c #AC2E39",
"a  c #AA2D33",
"s  c #AD3339",
"d  c #A93238",
"f  c #B33233",
"g  c #BA3435",
"h  c #BD3A35",
"j  c #BA3939",
"k  c #C43A2F",
"l  c #D13F2A",
"z  c #C23C34",
"x  c #C73933",
"c  c #D33F30",
"v  c #AE401D",
"b  c #B84F1B",
"n  c #9C4529",
"m  c #AC4F2C",
"M  c #B14522",
"N  c #AA502C",
"B  c #B15D2E",
"V  c #AC4D39",
"C  c #AD4836",
"Z  c #A95332",
"A  c #B6513B",
"S  c #C0551C",
"D  c #F45C1F",
"F  c #FA591B",
"G  c #ED690F",
"H  c #F36B1C",
"J  c #C74628",
"K  c #D74A2A",
"L  c #D8542C",
"P  c #C5413A",
"I  c #CF4439",
"U  c #D34434",
"Y  c #D4443A",
"T  c #DC4C39",
"R  c #DB4834",
"E  c #E34B2C",
"W  c #FE4F2B",
"Q  c #EF5B22",
"!  c #ED522C",
"~  c #FC5325",
"^  c #F45B24",
"/  c #FB5A27",
"(  c #F4522E",
")  c #FB522B",
"_  c #FA5C2A",
"`  c #F45727",
"'  c #E84C34",
"]  c #FE4D31",
"[  c #EC5431",
"{  c #E6523B",
"}  c #EB5138",
"|  c #FA5233",
" . c #F55434",
".. c #C26120",
"X. c #D1673D",
"o. c #CB7832",
"O. c #ED6321",
"+. c #F56424",
"@. c #F96324",
"#. c #F56A2C",
"$. c #FA6E2C",
"%. c #F86629",
"&. c #E77929",
"*. c #F67425",
"=. c #F4732C",
"-. c #F67526",
";. c #F96830",
":. c #EE7636",
">. c #F47932",
",. c #F67733",
"<. c #E46938",
"1. c #8D2D41",
"2. c #8C3443",
"3. c #8E3C4C",
"4. c #953E45",
"5. c #933C4B",
"6. c #963341",
"7. c #943F52",
"8. c #974652",
"9. c #9C4252",
"0. c #984959",
"q. c #9A575E",
"w. c #96424A",
"e. c #A44951",
"r. c #A2505D",
"t. c #A84646",
"y. c #BA6C46",
"u. c #9C5763",
"i. c #AE5C6D",
"p. c #A5626D",
"a. c #A9706A",
"s. c #A56573",
"d. c #A7717A",
"f. c #B3727A",
"g. c #B3696C",
"h. c #D44947",
"j. c #E54A40",
"k. c #C16543",
"l. c #D26B45",
"z. c #CF7842",
"x. c #DB754D",
"c. c #D57650",
"v. c #F07945",
"b. c #F9862B",
"n. c #F98D2C",
"m. c #F38D27",
"M. c #F8972C",
"N. c #F88B35",
"B. c #FC9D35",
"V. c #FD9538",
"C. c #E78A3B",
"Z. c #FBA52B",
"A. c #FDB52E",
"S. c #FABA2B",
"D. c #FEA436",
"F. c #FEAB36",
"G. c #FEA33C",
"H. c #FFAD3A",
"J. c #FEB333",
"K. c #FEBB32",
"L. c #FDB23A",
"P. c #FBC32E",
"I. c #FEC332",
"U. c #FECD37",
"Y. c #FDD939",
"T. c #CF894F",
"R. c #D78F46",
"E. c #D9934A",
"W. c #D7835E",
"Q. c #DE945B",
"!. c #E5994C",
"~. c #F39D4B",
"^. c #E79A5F",
"/. c #E98949",
"(. c #DDA040",
"). c #EDAB4E",
"_. c #EEA64C",
"`. c #FEAA42",
"'. c #FDA649",
"]. c #FDAF48",
"[. c #FDB547",
"{. c #E8A959",
"}. c #F7A856",
"|. c #F4B455",
" X c #C2806F",
".X c #D88964",
"XX c #D49262",
"oX c #DA9D7F",
"OX c #C58A75",
"+X c #D8A078",
"@X c #F3B26B",
"#X c #E8AD73",
"$X c #E2B07E",
"%X c #FEC540",
"&X c #F6C15B",
"*X c #BA7E87",
"=X c #AF828A",
"-X c #B8838B",
";X c #BA8B94",
":X c #BE979E",
">X c #D3A097",
",X c #D7A789",
"<X c #E3AD8B",
"1X c #E5B890",
"2X c #D4B4A0",
"3X c #EACEA4",
"4X c #EEC8B2",
/* pixels */
"                                                                              ",
"                                                                              ",
"                                                                              ",
"                                  4X      0.1.3.;X                            ",
"                                  <X    5.: 1 1 ,                             ",
"                                  .X  f.= , ; 1 , q.                          ",
"                                OXx.C P z & , > 1 2.            1X            ",
"                        p.0.9.8.- c.t h a : f Y w : 8.    XX~.#X              ",
"    $X                2.a u p 2 . W.$ , > 1 1 y { f , V C.].Q.                ",
"    3X{.XX          4.< j.U w g J /.X > 1 : * > f h.9 Q.!..X                  ",
"      XX|.z.6 , 1 1 : > i : , , O ^.M z w % & , - C r Z  X                    ",
"        m !.!.n , 1 : < 4 = ; : @ }.Q W ) R w n ^.k.< 6                       ",
"        6 % R.&XB , : 1 $ X.w e K '.^ _ ^ ^ /.@Xm & , 7                       ",
"      -X, 2 9 o.@X- * & U /.:.| Q '.O.,.V.*.~.+ * : 1 5.                      ",
"      0.: g P % 8 * < U ) +.`.^ D '.m.m.F.b.[ q , : , 7.                      ",
"      7.2 I e , 3 > x | / N.n._ ^ D.J.A.J.b.! i 1 > j i u.                    ",
"      0., j q , 1 > L D n.F.F D B.L.J.A.F.%.[ # * = u T % d.                  ",
"      =X, > 2 : , t N.F.J.F.b.B.L.J.A.S.B.~ ) E E @ 9 T r 7                   ",
"      u., 1 1 : q <.H.Z.F.L.A.S.J.K.I.A.D.+.+.#.#.v.l.x.A , ;X                ",
"    s.; , 1 1 * k =.J.-.n.A.S.U.P.U.Y.K.L.L.[.].H.&.L % , 3 f.                ",
"    5., > & 2 = U ^ G.#.-.J.S.I.A.I.P.J.J.J.G H `.*.[ 0 : 1 ;X                ",
"    9.: < P & > R ) $._ ^ D.A.J.A.A.A.J.A.V.F @.G.+.E 0 1 7                   ",
"    *X3 < j.I > c ) ` ~ D m.J.A.S.K.A.J.D.+.] ;.#. .h * 2 e.                  ",
"      w.* y } h v >.~ / M.%XJ.J.A.J.Z.B.*.^ ) ~ ( k # > 2 -X                  ",
"        6.= 9 M |.R.J >.[.J.m.n.H.B.D ~ ^ b.$.~ ( w , : u.                    ",
"          e.y.{.Z $ B E.S ,.$.^ +.+.^ @.,.F.>.} R & 3 u.                      ",
"          W.oXa., V k.X l | ) ) ] $.G.L.L.J.b 0 & 2 q.                        ",
"        >X      2.d * * U ] ~ ~ W ~ #.&...|.(.- 2 1 3.                        ",
"                s.2 : , g | ~  .l T Y w & - {.).o : 5                         ",
"                  < , 1 & J { h > & , 1 , * t _.).o 5                         ",
"                  9., a q & & & > 4 2 1 : > s V T.{.N                         ",
"                    9.s h.Y z q : 1 < 4 4.r.i.*X  ,X}.+X                      ",
"                      g.t.d p 1 p.  :X                #X                      ",
"                          -Xf.                          2X                    ",
"                                                                              ",
"                                                                              ",
"                                                                              ",
"                                                                              "
};

/* XPM */
static xpm_row_t const explosion3[] = {
/* columns rows colors chars-per-pixel */
"50 41 222 2 ",
"   c #000000",
".  c #97331E",
"X  c #95311B",
"o  c #A93D19",
"O  c #8E2B2C",
"+  c #942B26",
"@  c #992A26",
"#  c #9B262C",
"$  c #942B2D",
"%  c #9B2A2D",
"&  c #96272D",
"*  c #973529",
"=  c #8D2C3A",
"-  c #8E2C30",
";  c #962734",
":  c #9A2633",
">  c #942933",
",  c #9A2A33",
"<  c #96263B",
"1  c #9A2539",
"2  c #942A3A",
"3  c #9A283A",
"4  c #993533",
"5  c #90333F",
"6  c #933837",
"7  c #A32D24",
"8  c #AB2E24",
"9  c #A22729",
"0  c #AC2729",
"q  c #A22B2C",
"w  c #AB2B2A",
"e  c #B32E2C",
"r  c #AD3327",
"t  c #A63529",
"y  c #BC352D",
"u  c #B7392C",
"i  c #B53822",
"p  c #AC2D31",
"a  c #A52832",
"s  c #A93837",
"d  c #B33735",
"f  c #C4392C",
"g  c #DC3E22",
"h  c #C43D34",
"j  c #C83D38",
"k  c #D53F34",
"l  c #A95115",
"z  c #AA492B",
"x  c #AB4625",
"c  c #BA4B2D",
"v  c #B9592A",
"b  c #A94637",
"n  c #AE5030",
"m  c #BA5B3C",
"M  c #FD571E",
"N  c #F9601D",
"B  c #C84328",
"V  c #C54925",
"C  c #D94625",
"Z  c #CF532F",
"A  c #DB5C2A",
"S  c #C4403B",
"D  c #CC4134",
"F  c #D64A36",
"G  c #D1443D",
"H  c #DE4A3A",
"J  c #D94836",
"K  c #D75E31",
"L  c #FE4F25",
"P  c #E6592A",
"I  c #E45923",
"U  c #FB5426",
"Y  c #F55922",
"T  c #F95D24",
"R  c #F5542D",
"E  c #FC532A",
"W  c #F75A2B",
"Q  c #FA5729",
"!  c #E94C36",
"~  c #E44D38",
"^  c #E74935",
"/  c #F34F34",
"(  c #E55134",
")  c #EE5635",
"_  c #E85439",
"`  c #F25432",
"'  c #FB5232",
"]  c #F5553A",
"[  c #C96828",
"{  c #DB7C28",
"}  c #D67835",
"|  c #D06C34",
" . c #EC6328",
".. c #F46429",
"X. c #F56C29",
"o. c #F76B27",
"O. c #E27A2D",
"+. c #F57C2C",
"@. c #F77729",
"#. c #EC6434",
"$. c #E46B3A",
"%. c #F66638",
"&. c #E67837",
"*. c #F87535",
"=. c #8F3D46",
"-. c #953544",
";. c #943C45",
":. c #993A46",
">. c #933B4A",
",. c #9C3A4A",
"<. c #973548",
"1. c #962843",
"2. c #A63944",
"3. c #B73C44",
"4. c #9F4B5B",
"5. c #954A54",
"6. c #9C535C",
"7. c #994E4A",
"8. c #A54A4D",
"9. c #A54449",
"0. c #AC5645",
"q. c #BF5845",
"w. c #A14B5E",
"e. c #A45459",
"r. c #A35050",
"t. c #BB6447",
"y. c #9D5561",
"u. c #A45C69",
"i. c #A55A63",
"p. c #A3636C",
"a. c #AC696B",
"s. c #AA6E7A",
"d. c #A76A76",
"f. c #B06C73",
"g. c #AD727A",
"h. c #B1717B",
"j. c #D54A42",
"k. c #E75841",
"l. c #C66A45",
"z. c #C1694A",
"x. c #DC6C4D",
"c. c #CA7B47",
"v. c #C17F59",
"b. c #D57C58",
"n. c #E46B45",
"m. c #F96D40",
"M. c #E07F4C",
"N. c #E0705E",
"B. c #C47E6F",
"V. c #D87762",
"C. c #F5842D",
"Z. c #FD952E",
"A. c #FA8333",
"S. c #FA8C31",
"D. c #F08B33",
"F. c #E89239",
"G. c #F1943E",
"H. c #FD9A3C",
"J. c #FD9932",
"K. c #EA9232",
"L. c #FEA72D",
"P. c #FDB52C",
"I. c #FBBA2D",
"U. c #F8BA26",
"Y. c #FDA333",
"T. c #FEAC35",
"R. c #FDA53C",
"E. c #FAAD3D",
"W. c #F4A334",
"Q. c #FDB432",
"!. c #FCBB32",
"~. c #FEB13A",
"^. c #F6B035",
"/. c #F9C12E",
"(. c #FBC433",
"). c #FDCC35",
"_. c #FECC3A",
"`. c #FDD137",
"'. c #FFD53C",
"]. c #FEDA3C",
"[. c #DC8348",
"{. c #D88747",
"}. c #D58055",
"|. c #CD8455",
" X c #E48448",
".X c #F48644",
"XX c #F38C49",
"oX c #EB9846",
"OX c #F69E44",
"+X c #F59549",
"@X c #EC9654",
"#X c #ED915A",
"$X c #FCAC43",
"%X c #F5A143",
"&X c #FEB143",
"*X c #EDA75D",
"=X c #C98C66",
"-X c #D88F60",
";X c #CF8077",
":X c #DD8771",
">X c #C9947B",
",X c #DEA97D",
"<X c #F0A460",
"1X c #ECAF6F",
"2X c #FFD641",
"3X c #A87A84",
"4X c #B47A83",
"5X c #B57782",
"6X c #B7838D",
"7X c #BA8C94",
"8X c #B88C97",
"9X c #BB939D",
"0X c #DB9B85",
"qX c #E19B85",
"wX c #DDA480",
"eX c #DBAF90",
"rX c #CAA792",
"tX c #E2B892",
"yX c #E5BDA4",
"uX c #EAC294",
"iX c #EDCEA6",
"pX c #EFDBB0",
/* pixels */
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                                                    iX        y.>.>.s.                              ",
"                                                    uX>X7X=.> > < ; > -.                            ",
"                                                    ,Xc , & # # > > > > <.                          ",
"                                                    v.b 2 : 3.j.G w & > 1 3X            pXuX        ",
"                0X                          7Xu.u.s.b b > > s B R ` p ; : 6.        iX1XtX          ",
"                  *X-X      6Xp.p.8X    8X<.2 > > ; * 2.& z [.G.A.Q ~ # ; p.    wX*X@XyX            ",
"                     X.Xq.,.; ; : & 7.u.2 1 : > > = * j J ( I C.R.o.` p ; 8.b. XOX&.                ",
"                      K c.* % e k H h q # , , : : : O % y ~ E Q A.C.R r @ F .X*.n.                  ",
"                      e.$ t.Z ' E X.#.^ / _ S a > $ + + s i C Q Q *.! 9 u m.Q x.                    ",
"                      <.: 7 %.%.@.R...' C 8 , + n [.F.K.&X$XY.X.E ` f : 7 ) N.                      ",
"                      1.: y ) V G.@.Q ..+.$.r v E.Q.P.P.P.Q.Q.H.L ! @ < % ;X                        ",
"                      2 < u S 0.+X .@.T.P.Q.%XR.P.P.Q.Q.Q.Q.P.Y.N R 8 2 g.                          ",
"                      > 2 # : q #.o.T.I.P.U.I.P.I.I.P.P.P.P.P.Q.R.o.J & 3X                          ",
"                      e.> < : w ) S.P.Q.Q.P.!._.'._.!.P.P.P.P.Q.Q.Z.) w =     p.= = 4.              ",
"                        ;.> > w k.O.P.P.P.Q.I.].].'.(./._.(.!.Q.P.J.` w $ 5.>.2 ; > : 2 4X          ",
"                          5 : % d o W.P.Q.I.I.'.].].].].].]./.P.P.T.&.w : > > ; $ + + s 0.          ",
"                          ;.< ; 9 h { Q.Q.I./.'.].].].].].].).P.Q.Q.oX. & O t m c.{.|.t.4           ",
"                        ;.> < % F ' J.P.P.I.'.'.).'.].].`.'.(.Q.Q.P.F.m l.} &XD.P i : : > 9X        ",
"                      5.; > : x *.M Z.P.Q.U.'.2X/.).].'.(._.I.Q.E.OXz > $ x !.Y.M ^ : ; 2           ",
"                      = : & p A S.E @.~.Q.P./.'.I.).].`./.I.P.^.l t # ; 3 v ~.R.T ~ # > :.          ",
"                    6X= : ; p #.H.Y T T.Q.Q.P./.I.(.].).(.I.P.Q.[ G w ; : { Q.A.` S : 1 d.          ",
"                    4X> : > % J #.%.W +.T.P.Q.P.P.).].'.!.P.Q.Q.O._ y ; t @XoXV r % ; :.            ",
"                      2 ; 2 3 a d 7 c V D.Q.Q.P.P.!.!.!.P.P.Q.P.+.' f > s b 6 > : : -.              ",
"                      e., ; ; > * l.b + [ ~.!.I.!.P.Q.Q.I.U.P.R...' y > > s.  d.p.4X                ",
"                        7Xi.8.n @Xc % % } Q.Q.P.P.P.P.P.T.~.Y.o.U ] w 2 5.                          ",
"                            qXXXA B.7.b.A X.W.L.Q.!.I.P.+.W Y Q ` B # ;                             ",
"                          :Xn.0X    =X. 8 D 7 P C.T.Q.Y.X.^ C f i #XX : -.                          ",
"                        V.qX      =X4 : D k 0 ! E T %.T ) 9 > . F.$XX < < 3X                        ",
"                      yX        rXr.2.9.H ' C C E L ' E H 9 v oXE.} z.* ; d.                        ",
"                                  4., 9.j.E E R g ( ( B 0 @ [.oX| @ * }.* a.                        ",
"                                  6.3 > b H / _ h 9 # ; , > 6 4 , 3 $ b #X|                         ",
"                                  8X2 ; 2 2.3.s , -.,.2 2 <.f.5Xi.w.h.    <XM.                      ",
"                                    u.3 3 : ; - 5       9X                  uX<X                    ",
"                                      g.:., > >.                                eX                  ",
"                                                                                                    ",
"                                                                                                    "
};

/* XPM */
static xpm_row_t const explosion4[] = {
/* columns rows colors chars-per-pixel */
"56 52 232 2 ",
"   c #000000",
".  c #380715",
"X  c #480B16",
"o  c #581113",
"O  c #6A1D1C",
"+  c #57152A",
"@  c #4C0C25",
"#  c #701D23",
"$  c #5B2F3E",
"%  c #78242D",
"&  c #792934",
"*  c #79464C",
"=  c #983518",
"-  c #B2321B",
";  c #8B252E",
":  c #9C262D",
">  c #952A2D",
",  c #9C292B",
"<  c #992827",
"1  c #983327",
"2  c #8D2D39",
"3  c #8D2734",
"4  c #962734",
"5  c #9B2633",
"6  c #942934",
"7  c #9B2932",
"8  c #96263B",
"9  c #93293A",
"0  c #98253A",
"q  c #93333E",
"w  c #9C343D",
"e  c #993636",
"r  c #8F342A",
"t  c #AB2924",
"y  c #A3262B",
"u  c #A3292B",
"i  c #AB2B2B",
"p  c #A62924",
"a  c #B32C2D",
"s  c #B52E24",
"d  c #AA3329",
"f  c #B4312A",
"g  c #BB342C",
"h  c #B93929",
"j  c #A63436",
"k  c #B73835",
"l  c #A82932",
"z  c #CC3C2D",
"x  c #C4362B",
"c  c #C43B30",
"v  c #CA3D33",
"b  c #C22F24",
"n  c #B5511C",
"m  c #B2501B",
"M  c #9B4435",
"N  c #A84B24",
"B  c #B94628",
"V  c #B5582C",
"C  c #B8543D",
"Z  c #AE4E32",
"A  c #B96431",
"S  c #D24C1D",
"D  c #DE5A1C",
"F  c #F75B1E",
"G  c #F6641F",
"H  c #D7452B",
"J  c #C85B26",
"K  c #D95626",
"L  c #CC4333",
"P  c #C54336",
"I  c #D34333",
"U  c #DC4432",
"Y  c #D14C32",
"T  c #D24339",
"R  c #DC4A38",
"E  c #DA5836",
"W  c #C94E2B",
"Q  c #E54C2D",
"!  c #EA4C2E",
"~  c #E6492C",
"^  c #F34E2D",
"/  c #FD4E2C",
"(  c #E65629",
")  c #FC5326",
"_  c #F45B25",
"`  c #FA5C25",
"'  c #F5552D",
"]  c #FC522B",
"[  c #F65C29",
"{  c #F85827",
"}  c #E34C33",
"|  c #EB4D32",
" . c #EB4C3B",
".. c #E34835",
"X. c #F74E33",
"o. c #EC5233",
"O. c #EB523B",
"+. c #E9583B",
"@. c #F55334",
"#. c #FB5232",
"$. c #F3523B",
"%. c #F35A33",
"&. c #C96B38",
"*. c #D67637",
"=. c #CB602D",
"-. c #EA692B",
";. c #F76727",
":. c #EC7A27",
">. c #F77828",
",. c #E1693B",
"<. c #F36B36",
"1. c #ED7736",
"2. c #F87634",
"3. c #942E43",
"4. c #942642",
"5. c #8D3B41",
"6. c #8D394C",
"7. c #933543",
"8. c #993844",
"9. c #993F50",
"0. c #A63A42",
"q. c #96434A",
"w. c #984B54",
"e. c #974957",
"r. c #9A535D",
"t. c #874653",
"y. c #A4454A",
"u. c #A44B50",
"i. c #A55450",
"p. c #9E5A65",
"a. c #A35664",
"s. c #A15D70",
"d. c #9D6D77",
"f. c #A76875",
"g. c #AB737E",
"h. c #B1747E",
"j. c #AE686B",
"k. c #DC5F43",
"l. c #E65845",
"z. c #DA664F",
"x. c #DC7159",
"c. c #E76746",
"v. c #E5704B",
"b. c #D47467",
"n. c #E17866",
"m. c #D18E3F",
"M. c #F6822D",
"N. c #F9882A",
"B. c #F8952D",
"V. c #E48937",
"C. c #FA8A36",
"Z. c #E9923E",
"A. c #FC9332",
"S. c #FC9C34",
"D. c #F59739",
"F. c #FBA92E",
"G. c #FDB52E",
"H. c #FBBA2C",
"J. c #FCB528",
"K. c #FDA532",
"L. c #FDAB36",
"P. c #FDA43C",
"I. c #FEAD3A",
"U. c #F3A232",
"Y. c #FDB433",
"T. c #FCBB31",
"R. c #FEB33A",
"E. c #FDBB3A",
"W. c #FCC42D",
"Q. c #F7C72F",
"!. c #FDC333",
"~. c #FDCB35",
"^. c #FDC53C",
"/. c #FDCD3B",
"(. c #F4C334",
"). c #FDDB34",
"_. c #FED43C",
"`. c #FDDB3B",
"'. c #FDD335",
"]. c #D98844",
"[. c #EE9241",
"{. c #F59547",
"}. c #EC8F52",
"|. c #FBAB45",
" X c #FAB646",
".X c #CD877A",
"XX c #DE8676",
"oX c #D89576",
"OX c #DA906E",
"+X c #E28777",
"@X c #E89D7F",
"#X c #D7A862",
"$X c #E7A971",
"%X c #FDC742",
"&X c #FED341",
"*X c #FDDA43",
"=X c #FBDB4D",
"-X c #FBD849",
";X c #FBDB52",
":X c #F6DE57",
">X c #F9CE52",
",X c #F8E15D",
"<X c #F8DC68",
"1X c #F7E36B",
"2X c #F8E678",
"3X c #AD7A83",
"4X c #B77984",
"5X c #99818A",
"6X c #B6848D",
"7X c #B58C93",
"8X c #BA9199",
"9X c #C69498",
"0X c #D9968A",
"qX c #E28A81",
"wX c #E39982",
"eX c #D5A797",
"rX c #D5AB82",
"tX c #E7BA87",
"yX c #E8A99B",
"uX c #E0AC87",
"iX c #D2ADA3",
"pX c #F2D492",
"aX c #FAE685",
"sX c #FDEA96",
"dX c #FDF190",
"fX c #E0D2B6",
"gX c #FCECA6",
"hX c #F9EDB4",
"jX c #FCF1B5",
"kX c #F9F0AB",
"lX c #FEF5C7",
"zX c #FEF3DC",
/* pixels */
"                                                                                                                ",
"                                                                                                                ",
"                                                                                                                ",
"                                                      yX                                                        ",
"                                                      wX                                                        ",
"                                                      @XeX                                                      ",
"                                                      #XrX                                                      ",
"                                                      ].oX                                                      ",
"                                                      *.OX                                                      ",
"                                                      ,.n.        f.a.a.f.                                      ",
"                                                      E c.  a.2 6 6 6 6 5 9 p.                                  ",
"                                e.6.t.                x.} w 9 7 7 6 6 > 6 5 6 p.                                ",
"          iX                r.2 4 7 4 9               qXR 7 i U  .' U i 6 6 5 9                   eX            ",
"            pXtX          w 9 9 7 : 7 5 9             0XT i o.] #.] ] R < 4 6 3               @XuX              ",
"              tX}.oX    e.7 7 a z I T z 7 *     5.e.    k h @.) ) ] ] O.y 7 4 2           +Xc.yX                ",
"                OX<.k..Xy.w L ] ] ] ] @.k ; % 3 5 >     j , - D _ ) ] $.: 7 5 e.        +.'                     ",
"                  XX@.@...v #.] #.] #.I y x } } } ..T y.6 7 }. XP._ ] I 7 6 q       z.#.$.                      ",
"                    +X' ) ] ) ) ) ] H t a $.) ` ;.[ { } a L K |.T.:.O.t 5 6 r.  n.#.) +.                        ",
"                      z.' ) ] ] @.z s } Q #.{ C.Z.{.K #.^ ] ] _ B.V.j 4 u I U @.#.#.+.                          ",
"                    q.j ~ ] ] ] #.H ~ ] ) ` 2.J = 1 z #.] ) #.] ! i 6 < h @.{ ) ) +.                            ",
"                  6.4 s Q ) ) ] ] #.] F M.I.|.&., a | ] ] #./ / @.s f } ' C.M.{ X.qX                            ",
"                  9 7  ./ #.;.;.) #.) >.R. XN < P %.` G ` ) ) ) ] ^ #.] ] ' 2.+.b.                              ",
"                  5 , } ] { S.S.{ ] { P.Z.= < : B M.K.R.L.N.F ) ] ] ] ) ] ] O.                                  ",
"                  2 < Y @.:.R.D.Q ) ;.{.W Y E ,.D.R.T.'._.^.S.;.{ ] ] ] { { T       w.7.7.w.                    ",
"                  r.6 u x =.R.*.u } Y Y ] >.K.Y.^._.`.`.`.~.G.K.A.C.;.) ^ ^  .8.7.4 6 > > 5 3.6X                ",
"                    6.3 5 6 A r 6 y , U ;.P.H.H.!.!.'.`.`./.~._.~.H.I.;.o.b $.i g v g y 0 8 > M                 ",
"                    5XX + + X & 6 5 7 Q N.T./.*X_.H.T.`.`.&X(._.~.H.G.A.o.t ..d @.) #.T < Z m.$X.X              ",
"                  d.& O + @ . % 4.4., ~ N.^.`.)./.>XaXaX-X=X(.T.~.T.J.B.2.S f , Q ) ] %.c.C M 1 u.              ",
"                5.6 a P i d ; ; 7 > 7 U M.&X`._.;XdXkXlX2XsX<X~.Q._.!.K.S.2.h [.-.) ] ) Q < 6 5 q.              ",
"              q.: v #.' <.#.~ i 1 C 4 g -.^.).-X<XdX1XaXjXlXsX*X`.`.&XY.F.C.( U.K.{ ] ] $.y 6 5 w.              ",
"            7X6 g @.) >.C.{ ) R =.].6 : H E.`.:XjXgX-X;XkXzXsX*X*X).~.H.G.S._  XL.;.] #. .y 6 4 a.              ",
"            s.7 I ) ;.L.L.{ ] ] C. X1 4 B ^.`.,XlXsX=X1XhXjX2X`.`.`.~.Y.Y.F.:.^.L.;.$...T 7 > 6 9X              ",
"            f.5 T ] ;.R.%X>.) / K |.V > A -X`.=XdX1XaXgXlX<X/.'.`.`.(.Y.Y.F.N.L.P.,.x i y 6 6 7.                ",
"            6X6 g { [ L.T.C.@...< N z.7 n %X*X`.-X:XaXgX2X&XH.!.^.!.H.G.Y.A.K }.B p 7 4 7 8 6 3X                ",
"              8.u | ) >.P.[.d 7 & # , f ( R.&X'.&X1XaXaX;XQ.(.~.!.T.J.G.L.1.h q q 6 6 9 9 3.g.                  ",
"              h.w k o.Q Y d > % X o c #.) N.E.W.~.-X;X;X`.).`.`.W.Y.G.L.1.L e       3Xg.8X                      ",
"                6Xy.w j j 3.e.$ X B @.] ^ { A.R.J.W.'.`.).)._./.Y.Y.J.V.p 6 6                                   ",
"                      7X        R @.o.z s $.] ;.>.B.R.^._.`./.T.Y.G.G.1.i 6 > 3X                                ",
"                              +.X.T t : f @.) { Q o.C.I.R.L.K.G.J.R.C.` | i Z i.                                ",
"                          qXl.n.j.7 7 , ! { 2.:.m &.n n J ( F >.N.;.) ) ) K [.V q.                              ",
"                        x.n.    p.6 : f #.] >.R.%X^. X}.Z i O.#.@.! @.) G |.I.E , h.                            ",
"                      b.      iX5.5 , c ' ) F A.I.|.*.N 1 : t g i , f -.R.E.B.@.i e.                            ",
"                  9XiX      fX  s.5 5 c #./ ] { ;.S p 6 9 4 4 6 4 4 , v.K.A.` ] U u.                            ",
"                                  6 5 a @.] ) X. .R j e.  8Xf.3X  e.a %.{ ) ) { ] z.                            ",
"                                  8.> > z @.' x i 5 6 6X            w P O. .T I @.@.XX                          ",
"                                  g.6 9 4 i c k , 6 8.              8Xi.0.j u.4X  c.<.0X                        ",
"                                    9.8 9 9 4 7 > q                                 oX}.                        ",
"                                      a.q 6 9 3.a.                                      $X                      ",
"                                                                                          pX                    ",
"                                                                                                                ",
"                                                                                                                ",
"                                                                                                                "
};

/* XPM */
static xpm_row_t const explosion5[] = {
/* columns rows colors chars-per-pixel */
"57 57 245 2 ",
"   c #000000",
".  c #2B0A1C",
"X  c #2B0A1A",
"o  c #340A14",
"O  c #33061B",
"+  c #340A1A",
"@  c #3B0A1B",
"#  c #3B0816",
"$  c #340A0E",
"%  c #2B0A21",
"&  c #2E0721",
"*  c #340921",
"=  c #3A0C21",
"-  c #460B1A",
";  c #48131A",
":  c #55141A",
">  c #4C1112",
",  c #671914",
"<  c #4A0D21",
"1  c #560F22",
"2  c #49172B",
"3  c #551522",
"4  c #5C1623",
"5  c #671827",
"6  c #791D29",
"7  c #651D31",
"8  c #781E32",
"9  c #4C2A3C",
"0  c #68242C",
"q  c #74232C",
"w  c #7C222B",
"e  c #742729",
"r  c #692934",
"t  c #732334",
"y  c #7B2334",
"u  c #782839",
"i  c #6D3C22",
"p  c #762B13",
"a  c #7C3746",
"s  c #70525A",
"d  c #7C6A75",
"f  c #786068",
"g  c #765765",
"h  c #952E1E",
"j  c #963319",
"k  c #851E26",
"l  c #8C2D2D",
"z  c #88282C",
"x  c #9C262C",
"c  c #952A2D",
"v  c #9A2A2C",
"b  c #972A25",
"n  c #993627",
"m  c #842533",
"M  c #8C2534",
"N  c #822932",
"B  c #8D2B34",
"V  c #8D2B3B",
"C  c #862A3A",
"Z  c #952634",
"A  c #9B2533",
"S  c #932933",
"D  c #992A33",
"F  c #95273A",
"G  c #982639",
"H  c #94293A",
"J  c #9A2C3C",
"K  c #88353C",
"L  c #983339",
"P  c #8F3B24",
"I  c #AD2D24",
"U  c #A32A2C",
"Y  c #AB2C2B",
"T  c #A22828",
"R  c #B52E2B",
"E  c #AD342D",
"W  c #A53629",
"Q  c #B9342A",
"!  c #A32532",
"~  c #AB2B31",
"^  c #A22C35",
"/  c #A53A35",
"(  c #B63834",
")  c #B32B30",
"_  c #C73B2C",
"`  c #C33B35",
"'  c #CD3E31",
"]  c #D23E32",
"[  c #A4501D",
"{  c #A74A1E",
"}  c #91502F",
"|  c #AA4727",
" . c #BA4628",
".. c #B6552C",
"X. c #AB4A38",
"o. c #B85B33",
"O. c #B44A35",
"+. c #BB6834",
"@. c #F8591D",
"#. c #D9462D",
"$. c #C95828",
"%. c #CC4635",
"&. c #DA4634",
"*. c #DA4A3C",
"=. c #D84934",
"-. c #C55839",
";. c #DC533A",
":. c #D1502B",
">. c #FB5425",
",. c #F4552D",
"<. c #FC532C",
"1. c #F85A27",
"2. c #E64C37",
"3. c #F64E35",
"4. c #EC5332",
"5. c #EA523B",
"6. c #EB5638",
"7. c #F55333",
"8. c #FB5232",
"9. c #F25638",
"0. c #E95028",
"q. c #C57737",
"w. c #CE7235",
"e. c #EC6629",
"r. c #F66827",
"t. c #EF7526",
"y. c #F87729",
"u. c #F46431",
"i. c #EB7A35",
"p. c #F97734",
"a. c #C74B1B",
"s. c #8A2A41",
"d. c #893848",
"f. c #933A49",
"g. c #983544",
"h. c #93364B",
"j. c #A33945",
"k. c #8D4655",
"l. c #994756",
"z. c #97525A",
"x. c #974345",
"c. c #AB4D4E",
"v. c #B26D4D",
"b. c #945A69",
"n. c #A45A67",
"m. c #906D77",
"M. c #A46A74",
"N. c #A96877",
"B. c #AA747B",
"V. c #B06A6F",
"C. c #E45B47",
"Z. c #E74D40",
"A. c #D66345",
"S. c #DD7159",
"D. c #CB7145",
"F. c #E96E48",
"G. c #DA7868",
"H. c #CB7872",
"J. c #E17862",
"K. c #D95340",
"L. c #DA843B",
"P. c #D59036",
"I. c #F8862A",
"U. c #F8982F",
"Y. c #E3883C",
"T. c #F98A34",
"R. c #E8973C",
"E. c #FA9836",
"W. c #E28928",
"Q. c #FCB62E",
"!. c #FABB2E",
"~. c #F6BC2C",
"^. c #FEAC3A",
"/. c #FDA638",
"(. c #FCB433",
"). c #FCBB33",
"_. c #FBB53A",
"`. c #FAB93C",
"'. c #EFA538",
"]. c #FDC435",
"[. c #FEC43B",
"{. c #FDCA37",
"}. c #FEDB36",
"|. c #FED33C",
" X c #FDDA3D",
".X c #FCD236",
"XX c #DD8A42",
"oX c #D19245",
"OX c #E38A47",
"+X c #ED9A47",
"@X c #DEA343",
"#X c #F7A946",
"$X c #F9B844",
"%X c #F0B24B",
"&X c #DD886F",
"*X c #D68677",
"=X c #E3927C",
"-X c #EB916F",
";X c #FCCC43",
":X c #FCC846",
">X c #FED342",
",X c #FCD943",
"<X c #FCD94C",
"1X c #FADD54",
"2X c #F7DA58",
"3X c #F8C754",
"4X c #FAE25A",
"5X c #FCDE68",
"6X c #F6C76D",
"7X c #FBE369",
"8X c #F9E478",
"9X c #EFE47B",
"0X c #867680",
"qX c #937F89",
"wX c #AD7B85",
"eX c #B06F80",
"rX c #99838B",
"tX c #A9858C",
"yX c #B5848B",
"uX c #B68892",
"iX c #BC9498",
"pX c #D58D81",
"aX c #D3978D",
"sX c #D09E9B",
"dX c #E3958A",
"fX c #DFA594",
"gX c #DCAE92",
"hX c #E7B196",
"jX c #F5DC8E",
"kX c #F9E787",
"lX c #FDEA94",
"zX c #FAE897",
"xX c #FCF499",
"cX c #FCEBA3",
"vX c #FAEBA7",
"bX c #FCF2AA",
"nX c #FCEDB6",
"mX c #FBF3BD",
"MX c #FAF2B5",
"NX c #DAC4A7",
"BX c #FEF5CC",
"VX c #FDF8C8",
"CX c #FDF5D6",
"ZX c #FCEEC5",
"AX c #FDF3E2",
/* pixels */
"                                                                                                                  ",
"                                                                                                                  ",
"                                                                                                                  ",
"                                                      pX                                                          ",
"                                                      &X                                                          ",
"                                                      -X                                                          ",
"                                                      F.fX                                                        ",
"                                                      u.=X                                                        ",
"                                                      9.&X                                                        ",
"                                                      F.=X        uXk.s.V V k.                                    ",
"                                                      H.aX    k.V Z Z Z Z Z Z V wX                                ",
"                                                          uXV G Z Z Z Z S H G Z C yX                              ",
"                                                        z.V Z Z A Y _ R v G G A D V                               ",
"                                              N.M.    f.S Z S U =.7.8.7.#.b S Z Z G                               ",
"                            f.B c S N.  n.g.G S b.    u l D A Q 7.<.8.<.<.%.x S Z G tX                            ",
"          fX              f.v I ] 2.Q / c Z S B d.rXs t S Z ( 5.,.1.<.<.8.9.Q S Z H                 hX            ",
"            S.          z.c Q 9.8.>.8.5._ Y U A S t @ u Z ! v W +X_.E.r.>.>.&.x S s.            =XdX              ",
"              6.S.  z.^ ( _ 8.<.1.>.<.8.<.>.2.( A B < y A R *.I j @X>X/.1.<.2.x S k.        fXC.dX                ",
"                5.E x ' ,.<.1.y.E.T.y.y.t.y.u.;.x Z 1 5 ^ =.<.3.*.a.$X].r.7.Q x Z         C.9.dX                  ",
"                  j.! 5.<.>.I.(.^.!.].|.{.).E. .S F 5 N U 2.8.<.8.>.y.T.1.2.! G d.    S.7.,.pX                    ",
"                  N.x 5.8.y.^.U.t.$X>X3XL.w.OXX.S Z v _ 0.<.<.8.<.>.<.,.2.Q A M m.H.4.<.6.aX                      ",
"                    x._ ,.#XY. .%. .o.P Z Z c v ! x %.u.p.T.y.r.,.>.8.2.T S m N ( 8.<.4.                          ",
"                    B.x  .OXb Z Z B B S z B M F G ( i.^.(.(.(.(.E.t.<._ z 1 - l #.8.4.aX          qX              ",
"                  V./ J O.X.c v w - y t # - y S c ;.Q.(.$XzXjX$X(./.r.2.! : , C.=. .0             m.d             ",
"              V.%.=.T.XXS m w %.;.: o @ + q Z n ..W.[.5XcXBXCXvX3X].U.7.Y k -. .: ; O X X 2 g       qXd           ",
"              *.<.r.Q.'.c.V > , %.O.m M N D -.#X$X|. X,X5XkXnXBXkX X(.u.E D , # . 3 7 3 7 u N B u m.              ",
"              =.>.r.Q.;X[ c t o @ z G D b w.6XcXlX<X,X8X7X X2X9XkX>X(.e.U 5 1 = X - m B S h %.#.U V B.            ",
"              c.7.1.^.%Xn 8 2 X * 5 S D.w.%XcXnXkX<X8XMX9X<X7XxX7X|.`.W. .( E z 3 5 M n L.+Xr.<.&.! C             ",
"              yX` 5.F...e * % X @ w ..$X(.6X8X8XlXcXBXCXbXlXlXnXbX4X,X{.^.r.7.( H F S o.].Q.E.1.8.~ B tX          ",
"                uXK e 4 + . . + r S w.(.~.kX7X1XbXCXAXAXZXjXkXzXmXkX4X X~.I.<.=.S H c | ;X!.^.$.9.( S B.          ",
"                  f X * . . . ; S z v.(.;XzXkX<XlXzXmXCXCXbX2X8XVXcXkX X).T.<.' S M b D.;XQ.$X| ] E B             ",
"                  2 . . X O X 0 M > } ~.1XMXMX1X7X2X8XvXCXmX2XlXCXcX5X].^.r.4.Y m 5 S -._.(.#XU A v K             ",
"            B.j.( L 7 - O % + C y O i _.<XbXBX5X,X<X1XcXVXmXcXmXmXlX<X.XU.1.2.l - O q D ..OX| S V K               ",
"          l.I 3.7.R x C 7 + < F y O > @X|.8XzX8X,X X,X4XkXBXBXzXnXkX,X.XE.<.5.5 X X = 8 l S Z V z.                ",
"        B.x #.,.r.Y...S B q 8 Z B - $ oX{.,X1XkX1X X}.1XkXkX8X1XkXlX>X).p.8.` 4 O # 3 l U Y ! S uX                ",
"        f.Y 4.,.T.[.P.Z v Z V y S M u P _.|.,X7X7X,X}. X X X X X8X7X:XI.1._ w - t s.c Y.i.7.&.v f.                ",
"        J Y ,.,.T.[.%Xb A G m # 7 H S n #X{.>X,X7X4X,X X X X X<X7X}.[.t.,.T < @ 5 H n :X/.@.7.) V                 ",
"        J D 7.>./.!.:X[ G Z C o O 3 u z XX(.).|.,X<X,X}.}. X X,X X|.(.y.2.S 3 X 0 S o.`./.1.7.) H                 ",
"        l.S ] >./.~.].+XS S H ; . . O # p R._.:X%XP.,X X}.}.|.|.[._.E.r.] S : & 7 S / i.p.<.Z.x S B.              ",
"        N.S T ;.p.t.E.XXS S S r * + > n O.h o.XX{ #X.X X}..X!.Q.U.I.T.e.U V o * u M D ( *.*.I c Z n.              ",
"          j.S T %.;.c.| Z Z c 6 5 n 5.K.> - w b h R.].{.[.).(.W.W.^.T.&.S 4 + = ; - e S A T x Z g.                ",
"            g.H c x.l.J g.l.d.k #.,.;., . . X + 4 L R.Q.(.'.L.w.D.| Q ^ t O % . . . o t M Z H h.                  ",
"              N.z.l.n.yX    H.` 2.%., $ + . % 9 qXM.D.#XR.} a y l N m Z q o = . % . & 9 tXiX                      ",
"                          G.9.%.v 6 z y u t 7       iXX.v.    m.g m.  c.l q u 4 < @ . d                           ",
"                        A.;.*XM.S S Z Z S H H d.              0XrX      S Z n o./ N r                             ",
"                    fXC.G.    wXZ I A.| j b c F H d.        0X0X      N.Z l +.$X$.A C                             ",
"                  *XG.        V ( 6.E._.#XR.q.c G f.              uXx.S v q.;X).e.~ S M.                          ",
"                *X            S ' ,.E.Q.).|.;X+.c H b.            B.B V W '.).T.,.` c l.                          ",
"              sX            eXc ' <.I.Q.).|.;Xo.c H                 wXS A.T.y.1.8.Q G l.                          ",
"                            n.v ( ,.1.^.!.]. X@Xn f.                  K v %.,.,.=.A G g.                          ",
"                  NX        l.S ~ 7.<.y.^.(.).$X/ l.                  B.H Z E I x G J -.F.                        ",
"                            n.S T &.,.@.y.t.$./ S N.                    n.Z F G l J uX  =XJ.                      ",
"                              H A ) 2.4.5.*.b D g.                          N.n.B.          &X                    ",
"                              M.H Z x U U x A g.wX                                            hX                  ",
"                                uXf.B D Z S l.                                                                    ",
"                                                                                                                  ",
"                                                                                                                  "
};


static xpm_row_t const ball_cannon[] = {
/* columns rows colors chars-per-pixel */
"60 60 220 2 ",
"   c #000000",
".  c #000001",
"X  c #010101",
"o  c #020202",
"O  c #030303",
"+  c #040404",
"@  c #050505",
"#  c #060606",
"$  c #070707",
"%  c #080808",
"&  c #090909",
"*  c #0a0a0a",
"=  c #0B0B0B",
"-  c #0C0C0C",
";  c #0d0d0d",
":  c #0E0E0E",
">  c #0f0f0f",
",  c #101010",
"<  c #111111",
"1  c #121212",
"2  c #131313",
"3  c #141414",
"4  c #151515",
"5  c #161616",
"6  c #171717",
"7  c #181818",
"8  c #191919",
"9  c #1a1a1a",
"0  c #1B1B1B",
"q  c #1c1c1c",
"w  c #1D1D1D",
"e  c #1E1E1E",
"r  c #1f1f1f",
"t  c #202020",
"y  c #212121",
"u  c #222222",
"i  c #232323",
"p  c #242424",
"a  c #252525",
"s  c #262626",
"d  c #272727",
"f  c #282828",
"g  c #292929",
"h  c #2A2A2A",
"j  c #2b2b2b",
"k  c #2C2C2C",
"l  c #2D2D2D",
"z  c #2e2e2e",
"x  c #2F2F2F",
"c  c #303030",
"v  c #313131",
"b  c #323232",
"n  c #333333",
"m  c #343434",
"M  c #353535",
"N  c #363636",
"B  c #373737",
"V  c #383838",
"C  c #393939",
"Z  c #3A3A3A",
"A  c #3b3b3b",
"S  c #3C3C3C",
"D  c #3d3d3d",
"F  c #3E3E3E",
"G  c #3F3F3F",
"H  c #404040",
"J  c #414141",
"K  c #424242",
"L  c #434343",
"P  c #444444",
"I  c #454545",
"U  c #464646",
"Y  c #474747",
"T  c #484848",
"R  c #494949",
"E  c #4B4B4B",
"W  c #4C4C4C",
"Q  c #4d4d4d",
"!  c #4E4E4E",
"~  c #4f4f4f",
"^  c #505050",
"/  c #515151",
"(  c #525252",
")  c #535353",
"_  c #545454",
"`  c #555555",
"'  c #585858",
"]  c #5A5A5A",
"[  c #5c5c5c",
"{  c #5D5D5D",
"}  c #5e5e5e",
"|  c #5F5F5F",
" . c #606060",
".. c #616161",
"X. c #626262",
"o. c #636363",
"O. c #646464",
"+. c #656565",
"@. c #676767",
"#. c #686868",
"$. c #696969",
"%. c #6A6A6A",
"&. c #2A2A2A",
"*. c #6C6C6C",
"=. c #6e6e6e",
"-. c #6F6F6F",
";. c #707070",
":. c #717171",
">. c #727272",
",. c #737373",
"<. c #757575",
"1. c #767676",
"2. c #777777",
"3. c #787878",
"4. c #797979",
"5. c #7a7a7a",
"6. c #7B7B7B",
"7. c #7C7C7C",
"8. c #7d7d7d",
"9. c #7f7f7f",
"0. c #808080",
"q. c #818181",
"w. c #828282",
"e. c #838383",
"r. c #848484",
"t. c #858585",
"y. c #868686",
"u. c #878787",
"i. c #888888",
"p. c #898989",
"a. c #8a8a8a",
"s. c #8B8B8B",
"d. c #8D8D8D",
"f. c #8E8E8E",
"g. c #8f8f8f",
"h. c #909090",
"j. c #939393",
"k. c #949494",
"l. c #959595",
"z. c #969696",
"x. c #979797",
"c. c #858585",
"v. c #9A9A9A",
"b. c #9B9B9B",
"n. c #B6AEAB",
"m. c #9D9D9D",
"M. c #9e9e9e",
"N. c #9F9F9F",
"B. c #a1a1a1",
"V. c #A4A4A4",
"C. c #A5A5A5",
"Z. c #a6a6a6",
"A. c #A7A7A7",
"S. c #a8a8a8",
"D. c #A9A9A9",
"F. c #AAAAAA",
"G. c #ACACAC",
"H. c #adadad",
"J. c #AFAFAF",
"K. c #b0b0b0",
"L. c #B1B1B1",
"P. c #b3b3b3",
"I. c #B4B4B4",
"U. c #b5b5b5",
"Y. c #b8b8b8",
"T. c #B9B9B9",
"R. c #bababa",
"E. c #BBBBBB",
"W. c #BCBCBC",
"Q. c #bdbdbd",
"!. c #808080",
"~. c #bfbfbf",
"^. c #C0C0C0",
"/. c #c2c2c2",
"(. c #c4c4c4",
"). c #C6C6C6",
"_. c #c7c7c7",
"`. c #c9c9c9",
"'. c #CACACA",
"]. c #CBCBCB",
"[. c #cccccc",
"{. c #CDCDCD",
"}. c #cfcfcf",
"|. c #D0D0D0",
" X c #d1d1d1",
".X c #d3d3d3",
"XX c #D5D5D5",
"oX c #d6d6d6",
"OX c #D7D7D7",
"+X c #D8D8D8",
"@X c #DADADA",
"#X c #DDDDDD",
"$X c #dedede",
"%X c #e0e0e0",
"&X c #E1E1E1",
"*X c #e3e3e3",
"=X c #E4E4E4",
"-X c #e5e5e5",
";X c #E6E6E6",
":X c #E7E7E7",
">X c #e8e8e8",
",X c #ebebeb",
"<X c #ECECEC",
"1X c #ededed",
"2X c #EEEEEE",
"3X c #f0f0f0",
"4X c #f2f2f2",
"5X c #F3F3F3",
"6X c #F4F4F4",
"7X c #f5f5f5",
"8X c #F6F6F6",
"9X c #f7f7f7",
"0X c #F8F8F8",
"qX c #F9F9F9",
"wX c #fafafa",
"eX c #FBFBFB",
"rX c #fcfcfc",
"tX c #FDFDFD",
"yX c #FEFEFE",
"uX c #ffffff",
/* pixels */
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                      . . . . . . .                                                     ",
"                                            . . . . . . . . . . . . . . . .                                             ",
"                                      . . . . . $ . . . . . $ . . . . . . . . . .                                       ",
"                                  . . . $ $ $ $ $ $ $ $ . $ . . . . . . . . . . . . .                                   ",
"                                . $ $ $ * > > > 1 1 > > > * * $ $ . $ . . . . . . . . . .                               ",
"                            . . $ $ > 5 5 r u a u r r 0 1 1 > * $ . $ . . . . . . . . . . .                             ",
"                          . . * > 5 r a x N N C N n n h u r 5 1 > * $ . . $ . . . . . . . . . .                         ",
"                        . $ * 1 r a N J E / _ _ / ! U D N h u r 5 > * $ $ . . . . . . . . . . . .                       ",
"                      . $ * 5 a N J / o.%.,.<.<.-.%.| _ U D n a r 5 1 * * $ $ . . . . . . . . . . .                     ",
"                    . $ > 5 a C ! | ,.0.g.l.v.l.h.r.6.-.| ! J N a u 5 > * $ . $ . . . . . . . . . . .                   ",
"                  . . * 5 a C / @.9.l.D.K.T.!.T.K.Z.l.r.,.o./ J n a r 5 > * * . $ . . . . . . . . . . .                 ",
"                . . * 1 u N ! %.r.n.U.)..X@X$XOX[./.K.n.r.<.o.! D n a 0 1 > $ $ . $ . . . . . . . . . . .               ",
"              . . $ > 0 x U o.0.n.U..X%X-X1X4X1X-X@X).J.n.r.-.| E C x u 5 1 > $ $ . $ . . . . . . . . . .               ",
"              . . $ 5 u D _ <.l.K.[.,X4X7XqXuX7X7X,X@X/.D.h.9.%./ J N a r 5 > * $ . . . $ . . . . . . . . .             ",
"            . . $ > 0 x U o.0.B./.$X7XqXqXuXuXuXqX7X%X`.U.n.r.-.] E C h r 5 1 * $ $ $ . . . . . . . . . . .             ",
"            . . $ 1 u N ! %.a.D.`.-XqXuXuXuXuXuXuXqX-X[.T.Z.g.<.o.! D x u 0 1 * $ $ $ . . . . . . . . . . . .           ",
"          . . . * 1 a C / -.g.D.`.,X7XuXuXuXuXuXuX7X-X.XT.Z.g.6.o./ J n a r 5 > $ $ $ . . . . . . . . . . . .           ",
"          . . $ > 5 a C / ,.g.D.).-X7XqXuXuXuXqXuX4X%X[.T.Z.h.6.o./ J N a r 5 > * $ $ . . . . . . . . . . . . .         ",
"        . . $ $ * 5 h C ! %.r.B.T.OX-X7XqXqXqX7X4X,X@X).U.n.g.<.o.! U N a r 5 > * $ $ . $ . $ . . . . . . . . .         ",
"        . . . $ > 5 a N ! @.9.l.K.).OX%X1X4X4X,X,X$X[.T.D.l.r.,.| ! J n a r 5 1 * $ $ . . . . . . . . . . . . . .       ",
"        . . . $ * 5 u n U ] -.r.n.K.!.`.@X$X@XOX.X`.!.J.n.a.6.%._ E D n a r 5 > * $ . $ . . . . . . . . . . . . .       ",
"        . $ . $ * 5 r h D ! o.<.a.n.D.K.!.)././.!.U.D.n.g.9.,.| ! J C x u 0 5 > * $ $ $ . . . . . . . . . . . . .       ",
"      . . . . $ $ 1 0 a n U / @.<.r.g.v.Z.D.Z.Z.Z.n.h.a.9.-.@._ E D N h u 5 1 > * $ . . . $ . . . . . . . . . . .       ",
"      . . . . $ $ > 1 r h N U / o.-.<.0.a.g.g.g.g.r.9.<.-.o._ ! J N x a 0 5 > > * $ $ . . . . . . . . . . . . . . .     ",
"      . . . . . $ * 1 0 u x N J ! ] o.%.,.<.<.<.<.,.-.o.] / ! J C x a u 0 1 > * * . $ . $ . . . . . . . . . . . . .     ",
"      . . . . $ $ * > 1 0 u h N D U ! _ ] | | | | | ] / ! U D N x a u 0 5 > > * $ . $ . . . . . . . . . . . . . . .     ",
"      . . . . . . $ $ > 5 0 u a n N D J E E E ! E E E J D C N x a r 0 5 1 > * $ $ . $ . . . . . . . . . . . . . . .     ",
"      . . . . . . $ $ * > 1 5 r u h x n N C C C C D N N x x h u r 0 5 1 > * $ $ $ . . . $ . . . . . . . . . . . . .     ",
"      . . . . . . . $ $ * > 1 5 0 r u a h x x x x x x h a u u r 0 5 1 > * $ * . $ $ . . . . . . . . . . . . . . . .     ",
"      . . . . . $ . . $ * * > > 1 5 5 0 r r u u u u u r r 0 5 5 1 1 > * * $ . $ . . . . . . . . . . . . . . . . . .     ",
"      . . . . . . . . $ . $ $ * > > 1 1 5 5 5 0 0 5 5 5 5 1 1 1 > * * $ $ $ $ . $ . $ . . . . . . . . . . . . . . .     ",
"      . . . . . . . . . $ $ $ $ * * * * > > 1 1 1 1 1 1 1 > > * * * $ $ $ . $ . . . . . . . . . . . . . . . . . . .     ",
"      . . . . . . . $ . . . . . . $ * $ * * * * * * > * * * * * $ $ $ . $ . . . . . . . . . . . . . . . . . . . .       ",
"        . . . . . . . . . . . $ $ . $ $ $ * $ $ * $ * $ $ $ $ $ $ . $ . . . $ . . . . . . . . . . . . . . . . . .       ",
"        . . . . . . . . . . . . . $ . $ . . $ $ $ $ $ $ $ $ . $ $ . $ . $ . . . . . . . . . . . . . . . . . . . .       ",
"        . . . . . . . . . . . . . . . $ . $ $ . . $ . . . $ . . . $ . . . . . . . . . . . . . . . . . . . . . . .       ",
"        . . . . . . . . . . . . . . . . . . . $ . . $ . . . . $ . . . . . . . . . . . . . . . . . . . . . . . .         ",
"          . . . . . . . . . . . . . . . $ . . . . . $ . . . . . . . . . . . . . . . . . . . . . . . . . . . . .         ",
"          . . . . . . . . . . . . . . . . . . . . . . . . . $ . . . . . . . . . . . . . . . . . . . . . . . . .         ",
"            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .           ",
"            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .           ",
"              . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .             ",
"              . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .               ",
"                . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .               ",
"                  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .                 ",
"                    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .                   ",
"                    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .                     ",
"                      . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .                       ",
"                          . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .                         ",
"                            . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .                           ",
"                              . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .                               ",
"                                  . . . . . . . . . . . . . . . . . . . . . . . . . . .                                 ",
"                                      . . . . . . . . . . . . . . . . . . . . . . .                                     ",
"                                            . . . . . . . . . . . . . . . . .                                           ",
"                                                  . . . . . . . . . .                                                   ",
"                                                                                                                        ",
"                                                                                                                        "
};

