
#include <stddef.h>

// needs the typedef xpm_row_t
#include <lcom/xpm.h>
/* XPM */
static xpm_row_t const fish_1[] = {
/* columns rows colors chars-per-pixel */
"50 50 175 2 ",
"   c #000000",
".  c #22121E",
"X  c #231121",
"o  c #41323E",
"O  c #473B45",
"+  c #5F525E",
"@  c #C7522F",
"#  c #CD5E2F",
"$  c #DF572E",
"%  c #D55F2E",
"&  c #DC5A2D",
"*  c #D64F3A",
"=  c #DC4E3E",	
"-  c #DB463E",
";  c #CD5533",
":  c #DD5335",
">  c #DE5930",
",  c #D55339",
"<  c #D9503B",
"1  c #F64E2F",
"2  c #F84D2E",
"3  c #E4562D",
"4  c #EB532E",
"5  c #E1582D",
"6  c #F2502E",
"7  c #E44B35",
"8  c #EC4C35",
"9  c #E54B3B",
"0  c #EB4D3A",
"q  c #E4473A",
"w  c #F44E33",
"e  c #F84D31",
"r  c #F14E39",
"t  c #E45433",
"y  c #EC5231",
"u  c #E45832",
"i  c #E3523B",
"p  c #EA503D",
"a  c #EC5D3D",
"s  c #F25031",
"d  c #F15134",
"f  c #F65A32",
"g  c #F25C3A",
"h  c #EE603E",
"j  c #E56E38",
"k  c #F46936",
"l  c #F5653A",
"z  c #F6773D",
"x  c #FA753F",
"c  c #F8793F",
"v  c #80757B",
"b  c #DA4B41",
"n  c #D24B44",
"m  c #D95541",
"M  c #C54750",
"N  c #C74953",
"B  c #E44D41",
"V  c #E85845",
"C  c #F45F40",
"Z  c #F66B40",
"A  c #F37544",
"S  c #F67C4B",
"D  c #E6755D",
"F  c #F57964",
"G  c #E68E3F",
"H  c #F5863B",
"J  c #F8803E",
"K  c #F6893D",
"L  c #F8893F",
"P  c #F48335",
"I  c #F3903F",
"U  c #EF8F4E",
"Y  c #E18441",
"T  c #F68E45",
"R  c #F98D44",
"E  c #F48E4A",
"W  c #FA8F48",
"Q  c #FA8542",
"!  c #ED9244",
"~  c #E59441",
"^  c #F39044",
"/  c #F6924D",
"(  c #F8924C",
")  c #F1895F",
"_  c #F39552",
"`  c #F99754",
"'  c #FA9956",
"]  c #F59959",
"[  c #F99D5C",
"{  c #F0A05C",
"}  c #ED8764",
"|  c #FA9760",
" . c #FC9E61",
".. c #E48177",
"X. c #EB8F7D",
"o. c #F09070",
"O. c #FAA466",
"+. c #F4A369",
"@. c #FAA468",
"#. c #F4A86F",
"$. c #EFA470",
"%. c #EEAD7C",
"&. c #F6A770",
"*. c #F4AA73",
"=. c #F6AE79",
"-. c #EFB07F",
";. c #F5B17D",
":. c #978D94",
">. c #9F989F",
",. c #AE8E84",
"<. c #B7A294",
"1. c #F29B8E",
"2. c #CDB09A",
"3. c #E4AA83",
"4. c #EEB589",
"5. c #ECBD8D",
"6. c #F1B387",
"7. c #F5B78A",
"8. c #F9B78C",
"9. c #F2BA8E",
"0. c #F1AA97",
"q. c #EFB09E",
"w. c #F6BE94",
"e. c #DDBFAB",
"r. c #EAB9AE",
"t. c #F2BEA6",
"y. c #F3B5A6",
"u. c #E1C392",
"i. c #F5C49C",
"p. c #F8C49C",
"a. c #D5C5BC",
"s. c #F8C5A0",
"d. c #F7C8A7",
"f. c #FBCCAA",
"g. c #ECD1AD",
"h. c #F6D1B2",
"j. c #F9D5B7",
"k. c #F4D4BB",
"l. c #F8D7BA",
"z. c #EEE3BE",
"x. c #DFDEDE",
"c. c #F0CAC0",
"v. c #F2D3C1",
"b. c #F8DDC0",
"n. c #F6D0CA",
"m. c #F7DACC",
"M. c #FBD5CC",
"N. c #F9DCD7",
"B. c #F4DED9",
"V. c #EFE4C6",
"C. c #EFE6CA",
"Z. c #FBE1CD",
"A. c #F6E9DD",
"S. c #FAE9D8",
"D. c #F6ECE1",
"F. c #FDECE4",
"G. c #F1EFEE",
"H. c #F9F0E5",
"J. c #FCF5ED",
"K. c #F7FEEA",
"L. c #FCF9EF",
"P. c #F3F6E5",
"I. c #EDFFF1",
"U. c #FDF7F3",
"Y. c #F4FEF3",
"T. c #FCFCF4",
"R. c #FEFDFA",
"E. c #FEFEFD",
"W. c #FDFEFE",
"Q. c #FEFFFE",
"!. c #FFFFFE",
"~. c #FFFFFF",
"^. c #FEFEFF",
"/. c #FDFEFD",
"(. c #FEFEFD",
/* pixels */
"                                                                                                    ",
"                                                                                                    ",
"                                      ; 8 w 4                                                       ",
"                                    s e 0 0 e e 3                                                   ",
"                                $ 8 0 2 e 8 9 2 e 3                                                 ",
"                                e e w 9 e w w 9 2 e &                                               ",
"                            5 w 9 w 1 e 9 e 1 w 9 2 s                                               ",
"                            7 w e 9 w 1 e 9 e e 8 8 1 t                                             ",
"                          4 e q w 2 0 8 1 e 9 e 2 9 e 6                                             ",
"                          w e e 9 w e 0 8 1 w 9 1 e 0 e                                             ",
"                        4 9 0 e 1 9 w e 0 w e 8 r 1 9 e u                                           ",
"                        7 e w 9 e 1 9 w e 0 w e 9 e 8 e 4                                           ",
"                      5 8 9 w 2 9 e e 9 e e 9 2 w 8 w 8 1                                           ",
"          6 1 4       : w w 0 8 e 9 w e 9 2 w 0 e 9 e 0 1                                           ",
"        & e 1 e s     t 8 9 0 0 0 e 9 w w 0 e 0 w 8 w 9 e                                           ",
"        4 0 e 1 9 s   i 0 9 9 = 9 0 e 0 9 8 9 w 9 C D X.0.v.Y.Y.                                    ",
"        3 e 9 e 2 9 4   > t w 8 0 B B 0 8 9 V } t.F.R././././././././.R.Y.                          ",
"        t w e 9 e 8 w u         5 t 7 9 V o.Z.R././././././././././././././.P.                      ",
"          9 e 1 9 e 9 6               j 7.T./././././././././././././././././.R.C.                  ",
"          e 9 w w 9 w 9 y           z.{ J././././././././././././././././././././.H.u.              ",
"          1 e 0 9 e 9 8 9         K.9._ T./././././././././././././././././././././.R.g.            ",
"          7 e 1 w 9 w 9 0 i     Y.H._ R *.A.R././././././././././././.R.R.R.R./././././.V.          ",
"          3 9 9 e e 9 8 9 p   I.R.k.R R T O.=.w.p.w.p.s.i.f.d.s.7.#.+.[ ] ] ] +.-.9.S.R.R.5.        ",
"            e 1 9 w e 0 e g v.R./.4.R R ( O.@.O.] R R R ( O.@.@.( R R R R T w.a.J.h.E [ +.^         ",
"            8 r e 9 0 e x 8././.R.+.R R ' @.O.O.( R R R ` O.O.O.R R R R R ;.v X G.x.w.R T R I       ",
"            w 8 0 8 w l T Z././.T.E R R [ @.O.@.W R R R [ O.O.` R R R R R 2.. X + o <.R R R ^       ",
"          3 e 8 0 9 8 A / T././.D.W R T O.@.O.O.R R R R [ O.@.( R R R R R <.X X X X ,.T R R !       ",
"        < 8 8 w d 0 0 A ` R././.A.T R k l A | O.R R R R O.O.O.T R R R R R h.O X X o 3.R R R !       ",
"      4 e 1 w r 9 8 q h W T././.A.T J w 9 0 8 Z Q R R W O.O.[ R R R R R R ] A.>.:.e./ R R R R       ",
"    3 1 w 0 9 w 8 0 0 0 c b././.D.T k 1 e 1 8 9 d x R ( O.O.[ R R R R R R R E ;.+.T R R R R R ^     ",
"    8 9 8 d e 9 r 8 0 y     T./.L.W g 9 0 0 9 9 - 9 a k  .@.[ R R R R R R R R R R R R R R R R R T   ",
"  t w e e 8 9 e 8 r 4         T.R._ f 2 2 e w 8 B b M N D @. .R R R R R R R R R R R R H R R R R R ~ ",
"  1 e 8 9 w e 0 w y             Y.$.l 0 9 8 8 8 0 9 8 e S @.O.T R R R R R R R R R R R P H L L K G   ",
"7 0 9 r e w 9 y &                 i.z w 1 w p 8 w F y.n.m.b.=./ R R R R R R R R R R R K R K K R ^   ",
"t e 1 e 8 0 s                       T f 8 9 d F M.R././././.l.' T R R R R R R R R R R R R R R R     ",
"5 1 8 9 i                           Y R } 1.N.R././././././.T.&.R R R R R R R R R R R R R R T       ",
"  5 t %                 @ i < * 9 B b S j.W./././././././././.l.( R R R R R R R R R R R T ^         ",
"                      & 8 8 9 9 8 w 9 0 ) T./././././././././.R.6.R R R R R R R R R R ^             ",
"                      : 0 w e 1 8 9 0 q y   T./././././././././.T.%.R R R R R R T !                 ",
"                      4 e 1 8 q 8 8 8 y       r.U././././././././.R.k.*.U ! T                       ",
"                        e q 8 2 0 w 3       : 0 n ..q.c.B.F.L.L.F.T.T.Y.                            ",
"                        & 6 e 9 8 y       : 9 B 0 9 4 < 9 8 p = i                                   ",
"                          y 9 w y         9 8 9 8 8 5   9 w 8 0 9 t                                 ",
"                          & s           , 8 9 0 8 8     * e 9 8 8 9                                 ",
"                                        & 8 0 8 9 t       8 0 e 9 8 i                               ",
"                                          0 B s <         ; 8 8 8 w =                               ",
"                                                            # 9 e 9 w m                             ",
"                                                                t w 9 y                             ",
"                                                                                                    ",
"                                                                                                    "
};

/* XPM */
static xpm_row_t const fish_2[] = {
/* columns rows colors chars-per-pixel */
"50 50 189 2 ",
"   c #000000",
".  c #241121",
"X  c #372734",
"o  c #453943",
"O  c #51444F",
"+  c #675A61",
"@  c #685C68",
"#  c #B65F37",
"$  c #BF643B",
"%  c #C9572F",
"&  c #CB5B2C",
"*  c #D55E2C",
"=  c #DB5C2D",
"-  c #D15D27",
";  c #CA4C3A",
":  c #DA463B",
">  c #D64F39",
",  c #DE4B3D",
"<  c #D7453A",
"1  c #C35C35",
"2  c #CA5D33",
"3  c #D45435",
"4  c #DC5433",
"5  c #D65C33",
"6  c #DA5B32",
"7  c #D45538",
"8  c #DB5A38",
"9  c #F64E2F",
"0  c #F84D2E",
"q  c #E4562E",
"w  c #EB542E",
"e  c #E1582D",
"r  c #F3502E",
"t  c #E64B36",
"y  c #EC4B35",
"u  c #E34739",
"i  c #E54B3B",
"p  c #EA4C3A",
"a  c #E44634",
"s  c #F44E33",
"d  c #F84D31",
"f  c #F14D39",
"g  c #E25333",
"h  c #EC5232",
"j  c #E4523B",
"k  c #E9513C",
"l  c #E8583C",
"z  c #F35132",
"x  c #F75C34",
"c  c #F3563B",
"v  c #D4612D",
"b  c #C46730",
"n  c #C16039",
"m  c #CA6430",
"M  c #F76837",
"N  c #F66F3A",
"B  c #F86C3A",
"V  c #F6733A",
"C  c #F57A3F",
"Z  c #F97A3F",
"A  c #C94649",
"S  c #DE4A42",
"D  c #D74C49",
"F  c #D6574B",
"G  c #D7584D",
"H  c #E44D41",
"J  c #E25049",
"K  c #E45444",
"L  c #F15E41",
"P  c #EA6040",
"I  c #EA6B46",
"U  c #F26144",
"Y  c #F26E46",
"T  c #FA7C44",
"R  c #F77B4C",
"E  c #F37243",
"W  c #E57A53",
"Q  c #F07459",
"!  c #F17F69",
"~  c #EE8E3F",
"^  c #F58537",
"/  c #F58639",
"(  c #F6883D",
")  c #E1923F",
"_  c #DA8440",
"`  c #D89A43",
"'  c #DF8B50",
"]  c #F68E45",
"[  c #F98D44",
"{  c #F58F4A",
"}  c #EC9243",
"|  c #E19646",
" . c #F19044",
".. c #F5914C",
"X. c #F8934C",
"o. c #F28F51",
"O. c #F88A58",
"+. c #F79857",
"@. c #F99955",
"#. c #F19759",
"$. c #F69C5B",
"%. c #FA9C5C",
"&. c #F99659",
"*. c #D3A14A",
"=. c #CC9D7E",
"-. c #F99F60",
";. c #FB9E6A",
":. c #E2817B",
">. c #EE9978",
",. c #EE9975",
"<. c #F09C7E",
"1. c #EEA16B",
"2. c #F7A365",
"3. c #FAA365",
"4. c #F4A36A",
"5. c #FAA469",
"6. c #F6A671",
"7. c #F4AA73",
"8. c #F4AE7C",
"9. c #F8AC76",
"0. c #9C8F87",
"q. c #9F9595",
"w. c #ACA5AA",
"e. c #B3AEB0",
"r. c #EF9B89",
"t. c #EC9D94",
"y. c #D7AB8B",
"u. c #DEB799",
"i. c #F4B384",
"p. c #F7B688",
"a. c #F2A89B",
"s. c #EDBD97",
"d. c #F9BF95",
"f. c #F4BE95",
"g. c #C5BDBE",
"h. c #E9B7A0",
"j. c #EEB5A8",
"k. c #F6B7AB",
"l. c #F4B6AA",
"z. c #F3BEB2",
"x. c #D3C897",
"c. c #D1CB99",
"v. c #F5C19B",
"b. c #F8C298",
"n. c #F7C7A2",
"m. c #F8C5A0",
"M. c #F6CCAA",
"N. c #F5C9A3",
"B. c #EECAB7",
"V. c #E5DEBC",
"C. c #FBD2B5",
"Z. c #F5D3BA",
"A. c #F9D8BD",
"S. c #E1E2B9",
"D. c #D9D4D1",
"F. c #F6CBC2",
"G. c #ECD4C0",
"H. c #F5DAC3",
"J. c #F9DBD2",
"K. c #EBE0C4",
"L. c #F5E1CC",
"P. c #FAE1CA",
"I. c #ECE9D4",
"U. c #F7E6D5",
"Y. c #FAE6D6",
"T. c #F2E6DA",
"R. c #F8E7D8",
"E. c #FAEADC",
"W. c #DDFFE4",
"Q. c #F9E7E0",
"!. c #F7ECE3",
"~. c #ECFDEC",
"^. c #E4FEE6",
"/. c #FCF3E9",
"(. c #F2FAEC",
"). c #F9FBE7",
"_. c #EFFEF0",
"`. c #F5FEF6",
"'. c #F4FDF4",
"]. c #FCFBF4",
"[. c #F7FEF8",
"{. c #FEFDF9",
"}. c #FFFEFD",
"|. c #FEFEFE",
" X c #FFFFFE",
".X c #FFFFFF",
"XX c #FEFFFF",
"oX c #FDFEFD",
"OX c #FEFEFE",
/* pixels */
"                                                                                                    ",
"                                                                                                    ",
"                                v                                                                   ",
"                            1 t d d 9 =                                                             ",
"                          * d f p p d d w                                                           ",
"                        1 i d 0 9 s u f 0 r                                                         ",
"                      * 9 s i p 0 9 d i y 9 r                                                       ",
"                      3 f d 9 s i y 9 9 y y d q                                                     ",
"                    = d p p d d 9 p p 0 9 y f 0 *                                                   ",
"                    3 f d s p p 9 0 f i d d p d r                                                   ",
"                  * d y i d 0 d i y d s u d d i d e                                                 ",
"                  6 d d 9 i i 9 9 p p d d i d a d w                                                 ",
"                  g p p d d s u f 0 y p d d i d p d                                                 ",
"                  h 0 d p p d d p p 0 f p 9 y f i d e                                               ",
"                  j p f d s u f 9 y p d y p d K Q r.B.`.`._.~.'.`.^.                                ",
"    * *           d d y i i d p p f y i y U <.Y.{..X.X.X.X.X.X.X.X.X.X[.(.                          ",
"  q d d z *       k p i p u i s s y p l >.E.{..X.X.X.X.X.X.X.X.X.X.X.X.X.X.XI.c.                    ",
"  z d d s p q     j p p i i H < H i I Z.{..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X{.K.                  ",
"  t i d 0 f p q   e w e e e e g j W m..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X].x.              ",
"  w d i p d f p q               S.#.P..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XV.            ",
"  2 y d s t f f p e             H.[ 8.]..X.X.X.X.X.X.X.X.X{./.U.A.b.i.6.4.4.8.7.i.H.U.M.|           ",
"    h i f d y p f u 6         ].p.[ [ $.b.C.C.M.n.d.i.i.p.9.2.] [ [ [ [ @.Z.D.].v.] [ [  .          ",
"    = 9 y i p d p p i $     [.{.4.[ [ @.5.5.5.X.[ [ [ %.5.5.$.[ [ [ [ ] u.o @ {.e.1.] [ ]           ",
"      s d d s p p y i k   [..X]...[ [ %.5.5.5.{ [ [ [ %.5.5.X.[ [ [ [ { 0.. . O . y.[ [ [           ",
"      4 t y d 0 d p z T C..X.X!.] [ [ 3.5.5.3.[ [ [ [ 3.5.5...[ [ [ [ { q.. . . . =.[ [ [ `         ",
"        r f p i p z B ../..X.XR.[ [ [ 3.5.5.3.[ [ [ ] 3.5.3.] [ [ [ [ ] G.X . . + 9.[ [ [ }         ",
"        = d y y y p T $.{..X.XU.[ [ ] 5.5.5.3.[ [ [ [ 5.5.3.[ [ [ [ [ [ 2.T.w.g.s.[ [ [ [ [ }       ",
"          y y y i y C +.{..X.XR.] [ [ 5.5.5.-.[ [ [ [ 5.5.3.[ [ [ [ [ [ [ { 7.3.[ [ [ [ [ [ [  .    ",
"        = d y u y i L ] /..X.X/.] [ Z R R O.%.] [ [ [ 3.5.3.[ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ }   ",
"        g u y s i y p E N..X.X{...Z y p i p y x M Z V &.5.3.] [ [ [ [ [ [ [ [ [ [ [ ^ [ [ [ [ ~     ",
"      3 f 9 y i y t i z ' (..X.X4.V d d 0 s p : S D A F 5.5...[ [ [ [ [ [ [ [ [ [ [ ^ / / / ( )     ",
"      9 9 y p s i f y e     ^..Xf.V f p i H y i S J H z ;.5.@.[ [ [ [ [ [ [ [ [ [ [ [ [ [ [ [ }     ",
"    e s i y d i s i h         W.H.C y d d y u y i y ! J./.Z.-.[ [ [ [ [ [ [ [ [ [ [ [ [ [ [  .      ",
"    p i s d i f i h               o.r f t y s i f a.{..X.X.Xi...[ [ [ [ [ [ [ [ [ [ [ [ [ }         ",
"  & f 9 d i s y y v               *.N i d s i c k..X.X.X.X.XE.$.[ [ [ [ [ [ [ [ [ [ [  .`           ",
"  e d y i d f y *                   _ x d i U F..X.X.X.X.X.X.XZ...[ [ [ [ [ [ [ [ ] }               ",
"  4 f y 9 y p =                 # ; : Y ,.a.Q.oX.X.X.X.X.X.X.X.XM.{ [ [ [ [ [ ]  .                  ",
"  4 f 0 y t =               n > H p i i P L.{..X.X.X.X.X.X.X.X.X.XL.8.{ ] } }                       ",
"  - d f i v             % i i i f y y p 6     T.{..X.X.X.X.X.X.X.X.X'.).                            ",
"    * 6                 f p y d y y i h       7 G :.t.j.z.z.j.h.                                    ",
"                        t s d f p s p *     5 p , y , i s y H g                                     ",
"                        q 0 f p d p h       4 p i f i p y f i i                                     ",
"                          e d d y f v       3 p i s i p p d i p m                                   ",
"                            * d p w         7 p p s , 2 y f p y 8                                   ",
"                              = e           6 p p s 1   g y y s 7                                   ",
"                                              i 4 b       i f y j                                   ",
"                                                            q i f                                   ",
"                                                              1 5                                   ",
"                                                                                                    ",
"                                                                                                    "
};

/* XPM */
static xpm_row_t const fish_3[] = {
/* columns rows colors chars-per-pixel */
"50 50 172 2 ",
"   c #000000",
".  c #23111F",
"X  c #230F21",
"o  c #221120",
"O  c #2B1927",
"+  c #4A3D47",
"@  c #433643",
"#  c #554953",
"$  c #776369",
"%  c #D65C2B",
"&  c #DD5A2C",
"*  c #CD4D38",
"=  c #D74B3D",
"-  c #DD4B3C",
";  c #C8563F",
":  c #D55234",
">  c #DC5335",
",  c #D35A30",
"<  c #DD5931",
"1  c #DB533A",
"2  c #F64E2E",
"3  c #F84E2E",
"4  c #E4562D",
"5  c #EB532E",
"6  c #E4592E",
"7  c #F3502F",
"8  c #E34937",
"9  c #EC4C35",
"0  c #E54B3B",
"q  c #EA4C3A",
"w  c #F44E33",
"e  c #F84E31",
"r  c #F14E38",
"t  c #E45532",
"y  c #EC5332",
"u  c #E35931",
"i  c #E45438",
"p  c #EF5639",
"a  c #EB5C39",
"s  c #F35232",
"d  c #F35837",
"f  c #F3523A",
"g  c #EF6439",
"h  c #F76636",
"j  c #F76839",
"k  c #F2633D",
"l  c #F37538",
"z  c #F97A3F",
"x  c #F57C3E",
"c  c #897E7C",
"v  c #CB484D",
"b  c #E04D42",
"n  c #E65C4A",
"m  c #E66445",
"M  c #EB6140",
"N  c #F76F44",
"B  c #ED744B",
"V  c #F77549",
"C  c #EF6C53",
"Z  c #E67158",
"A  c #E27155",
"S  c #F67F51",
"D  c #E46B60",
"F  c #EB7B67",
"G  c #F6873B",
"H  c #F7883D",
"J  c #F98A3F",
"K  c #F58335",
"L  c #E3913F",
"P  c #F98241",
"I  c #F68E44",
"U  c #F98D44",
"Y  c #F58E49",
"T  c #E59645",
"R  c #EC9344",
"E  c #EC9249",
"W  c #F39144",
"Q  c #F99046",
"!  c #F6914C",
"~  c #F9924C",
"^  c #FA8D56",
"/  c #F39654",
"(  c #F89653",
")  c #F49D5D",
"_  c #F99D5C",
"`  c #F49E63",
"'  c #F89963",
"]  c #F29869",
"[  c #E5897C",
"{  c #F29F7D",
"}  c #F2947C",
"|  c #D7A37D",
" . c #EFA26B",
".. c #F7A065",
"X. c #FAA466",
"o. c #F3A46B",
"O. c #FAA469",
"+. c #F7AA6D",
"@. c #F6AA73",
"#. c #F8AC75",
"$. c #F3A37F",
"%. c #F1AF7E",
"&. c #F8AE78",
"*. c #EAB373",
"=. c #A6A1A4",
"-. c #D1A283",
";. c #D8B095",
":. c #F5A18E",
">. c #F4B586",
",. c #F8B583",
"<. c #F8B488",
"1. c #F4BA8D",
"2. c #F8B88B",
"3. c #E8AA9B",
"4. c #F0A794",
"5. c #F6A999",
"6. c #E6BC9E",
"7. c #F5BB92",
"8. c #E0BCA1",
"9. c #DCC38C",
"0. c #DFC293",
"q. c #F8C194",
"w. c #F5C39B",
"e. c #D4C1B1",
"r. c #E3C1AA",
"t. c #F7C6A3",
"y. c #F8C7A7",
"u. c #F7C8A4",
"i. c #F6CBAA",
"p. c #F2C5B6",
"a. c #F4C2B8",
"s. c #F7CAB9",
"d. c #F7D2B3",
"f. c #F8D1B3",
"g. c #FAD9BF",
"h. c #F4D4BD",
"j. c #F0E2BA",
"k. c #EFCCC0",
"l. c #F3D7C1",
"z. c #F5D9C1",
"x. c #F7D4C8",
"c. c #F2DBCB",
"v. c #FADDC5",
"b. c #EDE2C4",
"n. c #F3E2CF",
"m. c #F9E2CD",
"M. c #F5E4D6",
"N. c #FAE5D6",
"B. c #F9E4DC",
"V. c #F6EBDA",
"C. c #F9EADB",
"Z. c #FAEDE3",
"A. c #ECFEEF",
"S. c #FDF5EC",
"D. c #F5FCEE",
"F. c #FDF8EE",
"G. c #F9F1E2",
"H. c #FDF5F3",
"J. c #F6FFF6",
"K. c #F7FEF3",
"L. c #FBFBF4",
"P. c #F7FFF8",
"I. c #FEFEFA",
"U. c #FDFEFD",
"Y. c #FEFEFD",
"T. c #FDFEFE",
"R. c #FFFFFE",
"E. c #FFFFFF",
"W. c #FEFFFF",
"Q. c #FDFDFD",
"!. c #FEFEFE",
"~. c #F3F1F2",
/* pixels */
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                            & 5 5 5 y                                                               ",
"                          > 0 9 e 2 e 2 t                                                           ",
"                        & e e r q 0 w e 2 y                                                         ",
"                        1 r 3 e 2 e 9 0 e 2 5                                                       ",
"                      5 e 9 q 9 w 2 2 e 0 9 3 y                                                     ",
"                      r 3 3 e e q 0 w e 2 9 9 e y                                                   ",
"                    4 9 q 0 w e 3 e 9 q e 2 9 9 2 &                                                 ",
"                    > e e e 9 0 9 2 2 e 0 r 2 q e s                                                 ",
"                    y q q r 2 2 r q 9 e e q 9 e 0 2 5                                               ",
"                    3 2 e 9 0 9 e 2 r 0 w e 9 9 9 r 2                                               ",
"                    0 9 e e 2 9 0 9 2 e q 9 e q p Z } l.J.J.J.P.P.J.                                ",
"                  % e w q 0 9 e 3 9 0 w e 9 m { C.I.E.E.E.E.E.E.E.E.E.Q.J.                          ",
"                    9 r e e 9 0 9 e e q n $.Z.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.F.b.                    ",
"                  % e 9 q 0 9 e 9 q 0 B v.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.Z.0.                ",
"4 7 3 e y &         q 0 q q 0 0 q n ] w.I.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.b.              ",
"5 e 2 e q 9 5       y r q q 0 0 n p./ d.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.V.            ",
"4 0 r e e 9 0 w 6   1 9 y y 5 a s.h.U _ m.I.E.E.E.E.E.E.E.E.I.I.H.C.m.g.f.i.i.i.g.C.E.I.G.          ",
"  e 9 0 q e e q 9 5           K.E.>.U U ~ &.q.t.w.7.1.>.>.2.,.#.! I U U U U U U U I +.<.o.R         ",
"  t r e w q 0 w 9 0 t       J.E.I.) U U _ X.X.X.~ U U U _ O.O._ U U U U U Q %.8.d.@.U U U I         ",
"    q 0 q r e 9 q q q 1   j.I.E.Z.Y U U _ O.X.X.Y U U U _ O.X.( U U U U U ;.+ # ~.=. .U U U         ",
"    & e e 9 q 0 q r q M Y C.E.E.N.U U U X.X.X...U U U U X.X.X.Q U U U U / c X o o . | U U U         ",
"      y e 3 2 e e q r z ..I.E.E.z.U U ~ X.X.O._ U U U ~ X.X.X.U U U U U I e.@ o O $ ` U U U R       ",
"        0 0 q q 9 r e P @.E.E.E.z.U U ~ X.X.X._ U U U ~ X.X._ U U U U U U ( u.r.6.` U U U U I       ",
"        & 2 e e r q 9 z O.E.E.E.z.U U ~ X.X.X._ U U U ~ X.X._ U U U U U U U U U U I U U U U U W     ",
"          4 q 0 q q q d Y F.E.E.c.U U ~ X.X.X._ U U U ~ X.O._ U U U U U U U U U U U U U U U U U U   ",
"            2 e q q 0 q k y.Q.E.C.Y U Q X.O.X._ I U U Y X.O._ U U U U U U U U U U U U H U U U U U R ",
"            w 0 w 9 q q 0 p D.E.L.Y U U ^ S V N h j g b A O...U U U U U U U U U U U U K J U U H L   ",
"          1 q e r q 0 9 9 6   A.I. .P d 9 q 0 0 - b v v s ' X.Q U U U U U U U U U U U G J G H U W   ",
"          w 3 r q 9 q 0 e         w.l 9 r e 9 0 q 0 - f 4.B.1.( U U U U U U U U U U U U U U U U R   ",
"        4 e r q e q 9 q u         9.x 2 w 0 q w 0 q 9 5.E.E.M._ U U U U U U U U U U U U U U I T     ",
"        5 9 0 e 9 w 0 y             E s 0 e r 0 9 q C H.E.E.I.7.Q U U U U U U U U U U I U W         ",
"        9 q e 9 q w 9 6               g 2 r 0 e 0 f x.E.E.E.E.S.o.U U U U U U U U U U I T           ",
"        9 2 w 8 e 0 s               ; = 9 0 e r 9 :.E.E.E.E.E.E.C.! U U U U U U U W R               ",
"        2 w 0 e r 9               * - 0 q r 5 0 F H.E.E.E.E.E.E.E.C.o.U U U U W T                   ",
"        r 0 w w 0 u             - 0 r 0 0 y   -.B.I.E.E.E.E.E.E.E.E.I.n.w.*.                        ",
"        9 w 2 0 t             - 0 w r 9 q <     0 D [ 3.a.k.c.K.D.D.                                ",
"        & 3 r i             0 q 9 e q 9 9       0 8 r q 9 b i                                       ",
"                            r q e q w 8 w       0 q q r q 0 <                                       ",
"                            q s e 0 2 0 y       - r q w q 0                                         ",
"                              2 2 e w 9 4       : 9 9 9 f >                                         ",
"                                  5 w y           0 w 0 9 1                                         ",
"                                    4             , e q q                                           ",
"                                                    % q 0                                           ",
"                                                      : <                                           ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    "
};

/* XPM */
static xpm_row_t const fish_4[] = {
/* columns rows colors chars-per-pixel */
"50 50 180 2 ",
"   c #000000",
".  c #BF5F36",
"X  c #D35D2C",
"o  c #DB5B2D",
"O  c #DE4F37",
"+  c #D14F3F",
"@  c #DD4C3B",
"#  c #CF5432",
"$  c #C65D31",
"%  c #CA5E33",
"&  c #C2523E",
"*  c #D55435",
"=  c #DB5335",
"-  c #D55935",
";  c #DD5B31",
":  c #D55638",
">  c #D9553C",
",  c #F64E2E",
"<  c #F84D2E",
"1  c #E5562E",
"2  c #EB542E",
"3  c #E1592D",
"4  c #F2502E",
"5  c #E64A36",
"6  c #EC4C35",
"7  c #E24739",
"8  c #E54B3B",
"9  c #EA4C3A",
"0  c #F44E33",
"q  c #F84E31",
"w  c #F04E38",
"e  c #E45532",
"r  c #EC5232",
"t  c #E25931",
"y  c #E6513C",
"u  c #EB513C",
"i  c #EF593D",
"p  c #EC5C34",
"a  c #F35033",
"s  c #F35E37",
"d  c #F1533C",
"f  c #C5622C",
"g  c #CC622B",
"h  c #D3612D",
"j  c #D9602B",
"k  c #CC6333",
"l  c #D86837",
"z  c #D9693D",
"x  c #EC633B",
"c  c #F36436",
"v  c #F46D3B",
"b  c #F9683A",
"n  c #F77039",
"m  c #B97145",
"M  c #B7734B",
"N  c #CF4A4E",
"B  c #DE4C42",
"V  c #DD5344",
"C  c #C84851",
"Z  c #E14B41",
"A  c #E84C40",
"S  c #E65D44",
"D  c #E45B4A",
"F  c #F45740",
"G  c #C17E56",
"H  c #EB664F",
"J  c #EB6D49",
"K  c #F76D42",
"L  c #F1674D",
"P  c #F77247",
"I  c #F6774A",
"U  c #F97D42",
"Y  c #E5863E",
"T  c #F58539",
"R  c #F8873A",
"E  c #F68B3D",
"W  c #F48233",
"Q  c #D7834C",
"!  c #CE9B40",
"~  c #D89540",
"^  c #D39A42",
"/  c #DC9749",
"(  c #D48C5C",
")  c #F78E45",
"_  c #F98D44",
"`  c #F58F49",
"'  c #F88E48",
"]  c #F98443",
"[  c #E29442",
"{  c #EC9244",
"}  c #EB934E",
"|  c #F19142",
" . c #F5924D",
".. c #F9934C",
"X. c #F08B5F",
"o. c #FA8453",
"O. c #EE9050",
"+. c #F29454",
"@. c #F99552",
"#. c #F89956",
"$. c #F39458",
"%. c #F69959",
"&. c #F99C5C",
"*. c #F28063",
"=. c #ED966C",
"-. c #F5916D",
";. c #E6877C",
":. c #F49B75",
">. c #DEBE7F",
",. c #EFA56F",
"<. c #FAA366",
"1. c #F5A46C",
"2. c #FAA468",
"3. c #F4AB72",
"4. c #F9A974",
"5. c #F6B17D",
"6. c #F59480",
"7. c #F4B484",
"8. c #F6B98C",
"9. c #FAB481",
"0. c #EAAA9E",
"q. c #F2A997",
"w. c #EFBC97",
"e. c #E8B99B",
"r. c #F1BD95",
"t. c #F5BEB0",
"y. c #D5C18E",
"u. c #F4C097",
"i. c #F8C293",
"p. c #F8C29B",
"a. c #F5C9A5",
"s. c #F8C8A5",
"d. c #F4CAA9",
"f. c #F8CEAD",
"g. c #E0C8B1",
"h. c #F4C8B6",
"j. c #E9DFBA",
"k. c #E5D5B4",
"l. c #F6D1B5",
"z. c #FAD6BE",
"x. c #F7D8BD",
"c. c #FAD3B4",
"v. c #F5CDC3",
"b. c #F7D5C2",
"n. c #F4DCC6",
"m. c #FBD9C4",
"M. c #F3DCD5",
"N. c #E6E3C3",
"B. c #F9E1CE",
"V. c #E4ECD7",
"C. c #FAE6D6",
"Z. c #F5E7DA",
"A. c #F7EBDC",
"S. c #F8ECDF",
"D. c #F8EADB",
"F. c #DFFCE1",
"G. c #F4ECE2",
"H. c #FAEEE6",
"J. c #FCEDE9",
"K. c #E6F7E2",
"L. c #E2FDE7",
"P. c #E7FEEA",
"I. c #E7FEED",
"U. c #EBFBEB",
"Y. c #EAFEED",
"T. c #EAF9E3",
"R. c #F8F3E4",
"E. c #FCF5EC",
"W. c #F3FAED",
"Q. c #EEFFF2",
"!. c #FDF7F1",
"~. c #FEFCF6",
"^. c #FEFEFA",
"/. c #FEFEFD",
"(. c #FDFFFE",
"). c #FFFFFE",
"_. c #FFFFFF",
"`. c #FEFFFE",
"'. c #FDFEFD",
"]. c #FEFEFD",
/* pixels */
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    ",
"                            f 2 a 1 o                                                               ",
"                            8 8 0 q < q 3                                                           ",
"                          0 < q 6 9 9 q q 2                                                         ",
"                        * 9 0 < q < a 8 0 < 4                                                       ",
"                      3 q q 5 8 6 < < < 9 9 q a                                                     ",
"                      : 0 < < < 6 5 5 q < 0 9 q 1                                                   ",
"                    X a 5 5 9 0 < < 6 7 a < 0 9 < o                                                 ",
"                    # 6 q < 0 9 9 q < q 9 6 < 5 0 a                                                 ",
"                    2 w 8 5 q < q 9 9 q < 5 6 q 5 < ;                                               ",
"                    < q < 0 9 8 q < q 5 w < 9 6 6 6 4                                               ",
"                    9 8 6 q < q 9 9 < q 9 6 q 9 6 H *.e.K.Y.Q.P.Y.                                  ",
"                    < < w 9 9 q < 0 8 0 q 5 S -.b.E._._._._._._._._.'.U.U.                          ",
"                    8 5 0 q q 5 9 0 q 9 S :.C._._._._._._._._._._._._._._.'.V.                      ",
"  g 3 1             q 0 5 9 5 0 0 5 y J z.'._._._._._._._._._._._._._._._._._.'.N.                  ",
"o q < q 6 3         8 9 5 5 8 7 5 D =.i._._._._._._._._._._._._._._._._._._._._._.R.y.              ",
"o q q < 0 8 0 h     e 6 9 5 9 9 D h.$.l.'._._._._._._._._._._._._._._._._._._._._._.'.k.            ",
"X 5 7 0 < q 9 6 1   $ e t o o l b.l.) &.C._._._._._._._._._._._.'.'.!.H.S.S.S.H.~._._._.N.          ",
"  < q 6 8 5 q 5 8 e           P.'.7.) ) ..9.p.f.d.d.a.a.a.s.p.8.1.%.` ' ) ) ) ' ` 1.f.B.c./         ",
"  $ 8 a q 0 9 8 0 8 =       I.'.~.$.) _ &.<.<.<..._ ) ) &.<.2.&.) ) _ _ _ ) _ _ ' _ _ _ ' |         ",
"    r 5 8 9 0 0 5 8 9 >   j._._.A.' ) ) <.<.<.<.) ) ) ) <.<.2.@.) ) ) ) ) ) ) _ ) ) _ _ _ )         ",
"      q < q 6 6 5 9 6 v @.E._._.n.) _ ) <.<.<.&.) _ ) ) <.<.<...) ) ) ) ..Q m M G (  ._ _ _         ",
"      = 9 0 q < q q 6 ] 3._._._.l.) _ ..<.<.<.&.) ) _ ..<.<.<.) ) _ _ _ _ ..$.O.+...' _ ) _         ",
"        r 5 9 8 8 5 0 _ 7._._._.d.) _ ..2.<.<.#.) ) _ ..<.<.&.) ) ) _ _ ) _ ) ) _ _ _ ) ) ) [       ",
"          4 q q 9 6 0 U 5._._._.d.) _ ..<.<.<.#.) ) _ ..<.<.#.) ) ) ) ) ) ) ) ) _ _ ) ) ) ) ) !     ",
"          X 7 6 0 8 6 s $.~._._.l.) _ ..2.<.<.&.) _ _ @.<.<.#._ ) ) ) ) ) ) ) ) ) _ ) ) ) ) ) ) [   ",
"            < w 7 6 5 9 x z.'._.n.) _ ..<.2.2.&.) ) _ @.2.<.#.) _ _ ) ) ) ) ) ) ) ) ) _ ) ) ) _ _ ^ ",
"          t 6 9 0 9 6 6 9 z Y._.D.' ) ] o.I P K b v c @ X.2.&.) _ _ ) ) ) ) ) ) ) ) _ R _ ) ) ) {   ",
"          @ 0 q 5 0 5 5 0     F.~. .v a u 5 9 9 @ B C N i 2.<.) _ _ ) ) ) ) _ _ _ ) _ W T T T E     ",
"        ; < q 8 0 5 0 9 1       L.,.c 9 0 q 6 7 8 8 B F q.m.4..._ _ _ ) ) ) _ _ _ ) ) _ ) ) ) _ ~   ",
"        1 q 7 0 0 6 9 0           y.n q 6 5 0 6 9 8 a t._._.f.#._ _ ) _ ) ) ) ) ) ) _ _ ) ) ) {     ",
"        0 7 q q 8 q 8 ;             Y 5 0 < 6 6 6 w 6.'._._.E.1.' _ _ _ ) ) ) ) ) ) _ _ ) | ^       ",
"      $ 5 q < 8 q 5 r                 p q 6 9 q 9 L J._._._._.x...) _ ) ) ) ) ) _ _ _ ) {           ",
"      o q q 5 0 6 9 j               & B 0 6 < 5 d v._._._._._._.r._ ) _ ) ) _ ) _ ) {               ",
"      o q 9 0 a 9 ;               + 5 A 5 2 r 8 q.'._._._._._._.'.w.` ) _ ) ) | {                   ",
"      X 5 0 < 5 e             . @ 5 6 6 9 h   g.^._._._._._._._._._.Z.u.3.} ^                       ",
"        q < 0 y             : 9 8 q 8 6 6     f V ;.0.v.M.G.G.W.W.W.T.                              ",
"        3 a =             * 6 8 q 0 6 5 e     % 9 B 0 9 9 B k                                       ",
"                          ; 8 q 0 9 q u ;     ; 7 5 5 0 9 8                                         ",
"                          f 0 < 5 0 0 0 h     f Z 0 9 0 6 O                                         ",
"                            o a 0 < 5 4         8 6 0 9 6 -                                         ",
"                                  4 6 X         * 5 q 9 9 k                                         ",
"                                    f             e 0 5 8                                           ",
"                                                    e 6 :                                           ",
"                                                      = g                                           ",
"                                                                                                    ",
"                                                                                                    ",
"                                                                                                    "
};

/* XPM */
static xpm_row_t const fish_5[] = {
/* columns rows colors chars-per-pixel */
"50 50 181 2 ",
"   c #000000",
".  c #230F22",
"X  c #231121",
"o  c #473845",
"O  c #493E48",
"+  c #574C55",
"@  c #7E7379",
"#  c #BC6930",
"$  c #CE5F2E",
"%  c #D15D2F",
"&  c #DB5C2D",
"*  c #D5562D",
"=  c #CE4D3E",
"-  c #DE4A3E",
";  c #D94939",
":  c #C65D34",
">  c #C85038",
",  c #CB5C39",
"<  c #CD5933",
"1  c #D15735",
"2  c #DD5434",
"3  c #D05D31",
"4  c #DC5B32",
"5  c #F64E2F",
"6  c #F84E2E",
"7  c #E4572E",
"8  c #EA542F",
"9  c #E3582C",
"0  c #F4502F",
"q  c #E64A36",
"w  c #EC4B36",
"e  c #E34738",
"r  c #E54B3B",
"t  c #EA4D3A",
"y  c #F44E33",
"u  c #F84E30",
"i  c #F14F39",
"p  c #E55432",
"a  c #EB5233",
"s  c #E15831",
"d  c #E4513B",
"f  c #EB5339",
"g  c #EF593C",
"h  c #F55232",
"j  c #F75934",
"k  c #F4573A",
"l  c #CA642A",
"z  c #C6662B",
"x  c #D1622C",
"c  c #C56636",
"v  c #D46031",
"b  c #F56736",
"n  c #F46B3C",
"m  c #F86D39",
"M  c #F5623B",
"N  c #F6713A",
"B  c #F8703A",
"V  c #8D7976",
"C  c #C5454D",
"Z  c #DB4C44",
"A  c #DE5143",
"S  c #C64751",
"D  c #E54D41",
"F  c #E95040",
"G  c #E45A40",
"H  c #F35A41",
"J  c #DA7043",
"K  c #EA6042",
"L  c #EA6E4C",
"P  c #F46249",
"I  c #F37145",
"U  c #EF6E50",
"Y  c #EB6F5B",
"T  c #F56B52",
"R  c #E77654",
"E  c #ED7764",
"W  c #C7813D",
"Q  c #D58A3C",
"!  c #F5863A",
"~  c #F8873C",
"^  c #F48A3D",
"/  c #F98A3E",
"(  c #F58437",
")  c #D89A44",
"_  c #F68E45",
"`  c #F98D44",
"'  c #F58E49",
"]  c #E59443",
"[  c #ED9243",
"{  c #F49044",
"}  c #F6924D",
"|  c #F9934C",
" . c #EF8450",
".. c #F48659",
"X. c #EF9C5E",
"o. c #F59552",
"O. c #F99652",
"+. c #F79956",
"@. c #FA9955",
"#. c #F59D5D",
"$. c #F99C5A",
"%. c #D98264",
"&. c #DE877D",
"*. c #EC816D",
"=. c #F38D6C",
"-. c #F49E61",
";. c #FA9F60",
":. c #E29F7E",
">. c #ED947D",
",. c #FAA466",
"<. c #F5A66C",
"1. c #FAA468",
"2. c #F9A86F",
"3. c #F5A974",
"4. c #F5AE7B",
"5. c #8F858F",
"6. c #96908F",
"7. c #A19AA1",
"8. c #A9A1A4",
"9. c #BBB5B7",
"0. c #F2AF8B",
"q. c #EFB185",
"w. c #F3B284",
"e. c #F8B686",
"r. c #F4B689",
"t. c #F4B98A",
"y. c #F8B88C",
"u. c #ECAD9E",
"i. c #E7BC98",
"p. c #F8BE97",
"a. c #F5BF99",
"s. c #F3B995",
"d. c #C4B4AE",
"f. c #E6A7A2",
"g. c #DFC588",
"h. c #D3C496",
"j. c #F6C096",
"k. c #F8C29A",
"l. c #F5CCAC",
"z. c #F9CCA9",
"x. c #F4C8A4",
"c. c #F5C7BC",
"v. c #F4C8B2",
"b. c #EADEBD",
"n. c #F3D1B3",
"m. c #F8D4B6",
"M. c #F6D6B8",
"N. c #F7DABE",
"B. c #EBDFC4",
"V. c #F6DDCA",
"C. c #FBD7CC",
"Z. c #F7DCD4",
"A. c #E6EACC",
"S. c #F7E0C5",
"D. c #FAE5D3",
"F. c #F3EAD2",
"G. c #F9E8D6",
"H. c #FBE5DD",
"J. c #FAEBDD",
"K. c #E5F1D4",
"L. c #FBEFE4",
"P. c #EFFBE2",
"I. c #E9FDEC",
"U. c #FBF0E6",
"Y. c #FFF5ED",
"T. c #FBF2EA",
"R. c #F3FCEF",
"E. c #FCF8EF",
"W. c #F3F4E5",
"Q. c #FCF7F0",
"!. c #F5FEF5",
"~. c #FDF9F3",
"^. c #FDFEFA",
"/. c #FDFEFD",
"(. c #FFFFFD",
"). c #FEFFFD",
"_. c #FEFFFE",
"`. c #FFFFFF",
"'. c #FFFEFE",
"]. c #FDFEFE",
"[. c #FEFEFE",
/* pixels */
"                                                                                                    ",
"                                                                                                    ",
"                                l x                                                                 ",
"                              2 u 6 u 8 x                                                           ",
"                            a u q r i u 6 7                                                         ",
"                          1 y u u u t t u 5 8                                                       ",
"                        9 u q r i u 5 u r i u 8                                                     ",
"                        a u u 6 w r u 6 u t w 5 &                                                   ",
"                      p w r t u 5 u r w u 6 t i u z                                                 ",
"                      q u 5 w r w 6 u w t u 6 r u 8                                                 ",
"                    & y r w u 5 w r h 5 u r u y t u &                                               ",
"                    9 u 6 w r w 6 u t w u 5 r u t u 8                                               ",
"                    d t i u 6 w r y u i r u i r u t 6                                               ",
"                    u u q e w u u t t 5 i t 6 w w t a J                                             ",
"                    r w y 5 w r y 5 w t u i r M >.v.H.~./._._.^.!.I.I.                              ",
"    7 7 z           u i t r i u r t i i F L s.L._._._._._._._._._._._._.!.P.                        ",
"  8 6 u y p         r r t w D t u u i G 0.U./._._._._._._._._._._._._._._._./.A.                    ",
"  i 5 6 u e i x     f w w D r - - Z R y./._._._._._._._._._._._._._._._._._._._.T.h.                ",
"  a t w 6 6 r y 4   * a a a 8 p f u.X.S._._._._._._._._._._._._._._._._._._._._._./.b.              ",
"  & 6 i r w 5 t w &             A.n.` t./._._._._._._._._._._._._._._._._._._._._._._.F.            ",
"    r i 6 w q i w t &         I./.4._ ` 3.m.D.U.T.Y.Y.T.U.L.J.D.N.z.j.r.e.r.y.p.z.G._./.B.          ",
"    8 t r w u t r i r c     I.^.T.o.` ` $.1.1.1.} ' ' ' #.1.,.;.` ` ` ` ` _ 3.k.w._ 2.e.-.]         ",
"      5 5 w t r i t r d W K.^._.D._ ` ` ,.,.,.,._ ` ` ` ,.1.,.O.` ` ` ` ` i.6.7.^.M._ ` ` [         ",
"      2 i u u u w t w n $.Q._._.l._ ` | ,.1.1.$.` ` ` | ,.,.,.} ` ` ` ` -.@ X + 9.@ -.` ` [         ",
"        w t w w y u h ` y._._._.s.` ` | ,.1.1.+.` ` ` | ,.,.$.` ` ` ` ` 4.O . X X o 3.` ` {         ",
"        & 5 u i t r g ` z._._._.w.` ` @.,.,.1.O.` ` ` O.,.,.$.` ` ` ` ` #.8.X X X V o.` ` `         ",
"          8 r q r w 0 ` x._._._.w.` ` @.1.,.,.O.` ` ` @.1.1.O.` ` ` ` ` ` x.9.5.d.4.` ` ` ` ]       ",
"          s 6 y t w r N e._._._.q.` ` @.1.,.,.O.` ` ` @.1.1.} ` ` ` ` ` ` ` #.<.+.` ` ` ` ` ` ]     ",
"          a w t i r t r  .E._._.a._ ` @.1.1.1.O.` ` ` $.1.,.} ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` [   ",
"        < r i u r w r r a h.!._.l.` m j f a k M b B m I ,.,.O.` ` ` ` ` ` ` ` ` ` ` ` / ` ` ` ` _   ",
"        a 5 y r y r i t &     !.V.` y r w w w D - Z S C ..,.@.` ` ` ` ` ` ` ` ` ` ` ~ ( ` ` / ^     ",
"      9 6 w r u r i t a         W.' 0 u i w r t D Z r k =.4.#.` ` ` ` ` ` ` ` ` ` ` ` / ! ! / `     ",
"      8 w t u t w t i &           X.h r w u w r t w T Z._.Q.<.' ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` [     ",
"      r w 5 w w y t &               b u u t w y t P H._._._.l.O.` ` ` ` ` ` ` ` ` ` ` ` ` ` [       ",
"    4 u u w i u r a                 Q 5 e y u r H C._._._._.Q.<.` ` ` ` ` ` ` ` ` ` ` ` { )         ",
"    9 u w w u r a                   = K i 5 r H c._._._._._._.V.o.` ` ` ` ` ` ` ` ` _ [             ",
"    2 r w u w a                 > - r r f U E c._._._._._._._._.n._ _ ` ` ` ` ` { [                 ",
"    % h u i f               , r r i t r p   I.^._._._._._._._._._.V.<._ ` _ [ )                     ",
"      0 u 2               ; t r u w i t v     %.f.Z.^./._._._._._./.R.F.g.                          ",
"                        & w t 6 w w t a       r - r A Y *.&.:.                                      ",
"                        3 t 6 u q u t 7       t r r i t i r 4                                       ",
"                          0 u r u t i       $ t r Z y q r t &                                       ",
"                            & u u t a         t r Z w i r r v                                       ",
"                              l u p           t r r r u t t                                         ",
"                                l             s t t r u t r                                         ",
"                                                : # : u t r                                         ",
"                                                      & r p                                         ",
"                                                        , z                                         ",
"                                                                                                    ",
"                                                                                                    "
};

/* XPM */
static xpm_row_t const fish_6[] = {
/* columns rows colors chars-per-pixel */
"50 50 182 2 ",
"   c #000000",
".  c #23111F",
"X  c #231121",
"o  c #2A1B2B",
"O  c #311E2E",
"+  c #3E323C",
"@  c #4D3F4B",
"#  c #594B54",
"$  c #6D616D",
"%  c #BD6036",
"&  c #B76337",
"*  c #CF5A2D",
"=  c #DC5C2D",
"-  c #D55B2B",
";  c #D84B3A",
":  c #CD5C32",
">  c #CC5739",
",  c #D35435",
"<  c #DC5435",
"1  c #D25C32",
"2  c #DC5A35",
"3  c #DD523B",
"4  c #D45838",
"5  c #D5573A",
"6  c #F64E2F",
"7  c #F84E2F",
"8  c #E4562D",
"9  c #EC542E",
"0  c #E3582D",
"q  c #F3512F",
"w  c #E34B35",
"e  c #EC4B36",
"r  c #E44739",
"t  c #E44B3B",
"y  c #EB4D3A",
"u  c #F44E33",
"i  c #F84D31",
"p  c #F14E38",
"a  c #E55532",
"s  c #EC5232",
"d  c #E55832",
"f  c #EA523B",
"g  c #EB5F3C",
"h  c #F35133",
"j  c #F55E33",
"k  c #F35B3A",
"l  c #CD622C",
"z  c #C76829",
"x  c #C3642A",
"c  c #D1612C",
"v  c #C76532",
"b  c #C16A30",
"n  c #CB6530",
"m  c #E0673B",
"M  c #E9613F",
"N  c #F66038",
"B  c #E1763C",
"V  c #F8773C",
"C  c #F77A3D",
"Z  c #F87C3D",
"A  c #CE494C",
"S  c #DA4A45",
"D  c #D24F48",
"F  c #DE5048",
"G  c #E54D41",
"H  c #E94E40",
"J  c #E65E4A",
"K  c #DB6441",
"L  c #DB645E",
"P  c #E86A4B",
"I  c #F86944",
"U  c #F67141",
"Y  c #F07E41",
"T  c #F87E4F",
"R  c #F67158",
"E  c #F37A65",
"W  c #DF8E39",
"Q  c #F6863A",
"!  c #F7883C",
"~  c #F8883C",
"^  c #D79A41",
"/  c #F88340",
"(  c #F68D44",
")  c #F98D44",
"_  c #F78D48",
"`  c #F88849",
"'  c #F78443",
"]  c #E49442",
"[  c #EC9243",
"{  c #E4964C",
"}  c #F19144",
"|  c #F5924D",
" . c #F8924C",
".. c #F78951",
"X. c #F39552",
"o. c #F69856",
"O. c #FA9956",
"+. c #F49B5D",
"@. c #FA9C5B",
"#. c #F99557",
"$. c #D0966B",
"%. c #F89761",
"&. c #F49964",
"*. c #EF8779",
"=. c #E98875",
"-. c #F6A166",
";. c #FAA466",
":. c #F3A46C",
">. c #FAA468",
",. c #F2A771",
"<. c #F4AA73",
"1. c #F5AD7A",
"2. c #F7B27E",
"3. c #B79C8C",
"4. c #ADA09B",
"5. c #A69FA3",
"6. c #A9A2A7",
"7. c #B4ABAD",
"8. c #E69086",
"9. c #F0A98B",
"0. c #EDB488",
"q. c #F2B385",
"w. c #F6BC8D",
"e. c #F0A592",
"r. c #F7BF93",
"t. c #F8BE90",
"y. c #D2BEB3",
"u. c #EFB8AE",
"i. c #F6BAAD",
"p. c #F4BDA0",
"a. c #D5C798",
"s. c #F7C096",
"d. c #F5C59D",
"f. c #F8C39C",
"g. c #D2C4BA",
"h. c #F6C6A2",
"j. c #F7C9A4",
"k. c #F8C8A3",
"l. c #F5CCAD",
"z. c #F7CBB0",
"x. c #F7D1B2",
"c. c #F3D6BA",
"v. c #F9D7B9",
"b. c #CAC7C5",
"n. c #EADFC1",
"m. c #F9DECE",
"M. c #F6DAC9",
"N. c #E2DEDC",
"B. c #F8DCD5",
"V. c #DDE3C3",
"C. c #E1E7CC",
"Z. c #F7E2CD",
"A. c #F6E2C7",
"S. c #FAE6D5",
"D. c #F4E3DB",
"F. c #F3ECDC",
"G. c #FDE9D8",
"H. c #F1F8DE",
"J. c #F1F0D9",
"K. c #FBEEE5",
"L. c #FBEEE9",
"P. c #EFF7E7",
"I. c #EDFCE7",
"U. c #E7FDEB",
"Y. c #EAFEED",
"T. c #F0F7E7",
"R. c #F2F7E9",
"E. c #FAF3EA",
"W. c #F9F1E5",
"Q. c #EEFDF1",
"!. c #FCF7F1",
"~. c #F5FDF5",
"^. c #FDFAF5",
"/. c #FEFEFA",
"(. c #FEFFFD",
"). c #FDFEFE",
"_. c #FEFEFE",
"`. c #FFFFFF",
"'. c #FFFFFE",
"]. c #FDFEFD",
"[. c #FEFEFE",
"{. c #F5F5F6",
/* pixels */
"                                                                                                    ",
"                                                                                                    ",
"                                  a q 9 8                                                           ",
"                              l 9 t y i i q c                                                       ",
"                              w 7 6 i t e 7 i -                                                     ",
"                          - q e t i i i e y 7 i l                                                   ",
"                          < i i 6 y e 6 i p y 6 q                                                   ",
"                        8 i y e i 7 e t i i u y i =                                                 ",
"                        w i i e t i 6 i r i i e e 7                                                 ",
"                      0 7 y y 7 i y e 6 i r u i t i =                                               ",
"                      a i i e t i 6 y y i u r 7 p e 6                                               ",
"                    l e r p 7 i t p 7 e y 7 p y i t i 0                                             ",
"                    * 6 i y y i 6 y e 6 p y 7 y p t i =                                             ",
"                    a H e i u t u i y e 6 e p 7 r u e 9                                             ",
"    c q q 0         a i p y e i y e i y e 7 y e f P =.e.C.Y.U.U.                                    ",
"    0 i 7 i e       < y t y t y i e t y e t P 9.G.^.'.'.'.'.'.'.'.'.~.~.                            ",
"    a y 6 7 y p z   , t t t G ; t t y e P p.E.'.'.'.'.'.'.'.'.'.'.'.'.'.'.P.V.                      ",
"    0 p r i i r u   x 0 0 8 9 s w y J &.K.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.F.a.                  ",
"    : i i t u i r s               $.&.v.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'./.n.                ",
"      t e 7 e y i r d             A._ A.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.F.              ",
"      9 e r u p t p t 1         ~.q.) @.M./.'.'.'.'.'.'.'.'.'.'.'.'././././././.'.'.'.E.            ",
"      - 7 7 e t u y e t       ~.!.X.) ) O.<.t.f.s.d.d.d.k.k.f.w.:.-.X. . .| X.<.1.h.!./.c.          ",
"        t u 6 i e t e t 2   ~.'.S.( ) ) ;.;.;.;.) ) ) ) ;.>.;.O.) ) ) ) ) <.g.N.L.:.( X. .[         ",
"        d e t p 6 i y j ..W.'.'.l.) )  .;.;.;.@.) ) )  .;.;.;. .) ) ) ) o.4.O 6.{.g._ ) ) ]         ",
"          7 6 e t e h / w.'.'.'.0.) )  .;.;.;.o.) ) )  .;.;.;.( ) ) ) ) q.@ X O @ $ +.) ) ]         ",
"          a y y y y k ) v.'.'.'.1.) ) O.;.;.;.X.) ) ) O.;.;.O.) ) ) ) ) r.+ X X . # +.) ) [         ",
"          8 i u y t k ) M.'.'.'.:.) ) @.;.;.;. .) ) ) O.;.>. .) ) ) ) ) :.7.X X o 3.( ) ) )         ",
"        = e e t p r t ' x.'.'.'.:.) ) @.;.;.>. .) ) ) @.>.;. .) ) ) ) ) ) j.b.5.y.+.) ) ) ) [       ",
"        ; e i u t e r g 2.'.'.'.,.) j h k I T ` ) ) ) @.>.;. .) ) ) ) ) ) ) +.:. .) ) ) ) ) ) [     ",
"      s 7 i e y e t e p B T.'.'.q./ e y y t t e N V Z #.;.;. .) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) [   ",
"    = 7 e r e e e e y 0     Q.'.h.C i i p e y t S S A D &.;. .) ) ) ) ) ) ) ) ) ) ) ! ) ) ) ) ) [   ",
"    s t e 6 e t u t s         Y.c.C y y e i p y t F G p %.;.O.) ) ) ) ) ) ) ) ) ) ) Q Q Q Q ~ W     ",
"  1 e i 7 e e u t s             J.Y i i p t y e t p E i.m.d.+.) ) ) ) ) ) ) ) ) ) ) ( ) ) ) ) (     ",
"  8 i i t p i t s                 { q y e i e y k i./.'.'.!.:.) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ]     ",
"  h e t u u t s                     Y i 7 y e R B.'.'.'.'.'.l.| ) ) ) ) ) ) ) ) ) ) ) ) ) } ^       ",
"  e u i u t d                     & K U f f *.L.'.'.'.'.'.'.^.,.) ) ) ) ) ) ) ) ) ) ) ) [           ",
"  9 7 u t d                 % ; t r t M z.D./.'.'.'.'.'.'.'.'.S.| ) ) ) ) ) ) ) ) ( [               ",
"    9 < n               3 t y r p y y y m H.].'.'.'.'.'.'.'.'.'.Z.| ) ) ( ) ) } [                   ",
"                      = e t p i e e y s       B./.'.'.'.'.'.'.'./.E.d.>.X.} ^                       ",
"                      2 e i i y e e e       : r L 8.u.M.D.L.L.R.~.~.I.                              ",
"                        i p t u p y -       t t G t t e t t t b                                     ",
"                        0 u i u t s       : y G e y t p y y t -                                     ",
"                          l i e h -       5 e r e t y u y y t 2                                     ",
"                            = a           > y t h t : p y e p 4                                     ",
"                                          1 e y p >   a y e p 3                                     ",
"                                            , < v       t i y y                                     ",
"                                                        & h w e                                     ",
"                                                            , s                                     ",
"                                                                                                    ",
"                                                                                                    "
};
